-- Fallback 2:logo della rete
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/AllMusic.jpeg' WHERE image_url IS NULL AND rete = 'All Music';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ArchivioSteadycam.jpeg' WHERE image_url IS NULL AND rete = 'Archivio Steadycam';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Canale5.jpeg' WHERE image_url IS NULL AND rete = 'CAN 5';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Jimmy.jpeg' WHERE image_url IS NULL AND rete = 'Canal Jimmy';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CineMovie.jpeg' WHERE image_url IS NULL AND rete = 'Cine Movie';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CineCinemas1.jpeg' WHERE image_url IS NULL AND rete = 'CineCinemas 1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CineCinemas2.jpeg' WHERE image_url IS NULL AND rete = 'CineCinemas 2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ArchivioSteadycam.jpeg' WHERE image_url IS NULL AND rete = 'Cineclassic';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CinemaStream.jpeg' WHERE image_url IS NULL AND rete = 'Cinema Stream';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ComedyCentral.jpeg' WHERE image_url IS NULL AND rete = 'Comedy Central';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ComedyLife.jpeg' WHERE image_url IS NULL AND rete = 'Comedy Life';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Cult.jpeg' WHERE image_url IS NULL AND rete = 'Cult';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CultNetwork.jpeg' WHERE image_url IS NULL AND rete = 'Cult Network Italia';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/CurrentTV.jpeg' WHERE image_url IS NULL AND rete = 'Current TV';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Discovery.jpeg' WHERE image_url IS NULL AND rete = 'Discovery Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/DiscoveryRealTime.jpeg' WHERE image_url IS NULL AND rete = 'Discovery Real Time';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/DisneyChannel.jpeg' WHERE image_url IS NULL AND rete = 'Disney Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/DuelTv.jpeg' WHERE image_url IS NULL AND rete = 'Duel TV';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Fox.jpeg' WHERE image_url IS NULL AND rete = 'Fox';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/FoxCrime.jpeg' WHERE image_url IS NULL AND rete = 'Fox Crime';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/FoxLife.jpeg' WHERE image_url IS NULL AND rete = 'Fox Life';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Fx.jpeg' WHERE image_url IS NULL AND rete = 'FX';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/GayTv.jpeg' WHERE image_url IS NULL AND rete = 'Gay Tv';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/GXT.jpeg' WHERE image_url IS NULL AND rete = 'GXT';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/HallmarkChannel.jpeg' WHERE image_url IS NULL AND rete = 'Hallmark Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/HappyChannel.jpeg' WHERE image_url IS NULL AND rete = 'Happy Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/HistoryChannel.jpeg' WHERE image_url IS NULL AND rete = 'History Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ArchivioSteadycam.jpeg' WHERE image_url IS NULL AND rete = 'INN';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Ita1.jpeg' WHERE image_url IS NULL AND rete = 'ITA 1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/La7.jpeg' WHERE image_url IS NULL AND rete = 'La 7';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/MatchTvc.jpeg' WHERE image_url IS NULL AND rete = 'MATCH TV';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Mtv.jpeg' WHERE image_url IS NULL AND rete = 'MTV';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/MtvBrandNew.jpeg' WHERE image_url IS NULL AND rete = 'MTV Brand:New';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/MtvHits.jpeg' WHERE image_url IS NULL AND rete = 'MTV Hits';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Mtv.jpeg' WHERE image_url IS NULL AND rete = 'MTV Music Television';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/NatGeoChannel.jpeg' WHERE image_url IS NULL AND rete = 'National Geographic Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/OdeonTv.jpeg' WHERE image_url IS NULL AND rete = 'Odeon Tv';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Planet.jpeg' WHERE image_url IS NULL AND rete = 'Planete';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rai1.jpeg' WHERE image_url IS NULL AND rete = 'RAI 1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rai2.jpeg' WHERE image_url IS NULL AND rete = 'RAI 2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rai3.jpeg' WHERE image_url IS NULL AND rete = 'RAI 3';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiDoc.jpeg' WHERE image_url IS NULL AND rete = 'Rai Doc';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiEdu.jpeg' WHERE image_url IS NULL AND rete = 'Rai Edu 1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiEdu.jpeg' WHERE image_url IS NULL AND rete = 'Rai Edu 2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiFutura.jpeg' WHERE image_url IS NULL AND rete = 'Rai Futura';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiRadio1Logo2010.jpeg' WHERE image_url IS NULL AND rete = 'Rai Radio1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiRadio2Logo2010.jpeg' WHERE image_url IS NULL AND rete = 'Rai Radio2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiRadio3Logo2010.jpeg' WHERE image_url IS NULL AND rete = 'Rai Radio3';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiUtile.jpeg' WHERE image_url IS NULL AND rete = 'Rai Utile';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiNews24.jpeg' WHERE image_url IS NULL AND rete = 'Rai News 24';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiSatCinema.jpeg' WHERE image_url IS NULL AND rete = 'RaiSat Cinema';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiSatExtra.jpeg' WHERE image_url IS NULL AND rete = 'RaiSat Extra';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiSat.jpeg' WHERE image_url IS NULL AND rete = 'RaiSat Fiction';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiPremium.jpeg' WHERE image_url IS NULL AND rete = 'Rai Premium';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiSatRagazzi.jpeg' WHERE image_url IS NULL AND rete = 'RaiSat Ragazzi';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiSatShow.jpeg' WHERE image_url IS NULL AND rete = 'RaiSat Show';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/MgmChannel.jpeg' WHERE image_url IS NULL AND rete = 'MGM Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rete4.jpeg' WHERE image_url IS NULL AND rete = 'RETE 4';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ReteA.jpeg' WHERE image_url IS NULL AND rete = 'Rete A';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rete7.jpeg' WHERE image_url IS NULL AND rete = 'Rete7';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/ArchivioSteadycam.jpeg' WHERE image_url IS NULL AND rete = 'Sala Video Canale';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Sat2000.jpeg' WHERE image_url IS NULL AND rete = 'Sat 2000';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Sky1.jpeg' WHERE image_url IS NULL AND rete = 'Sky Cinema 1';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Sky169.jpeg' WHERE image_url IS NULL AND rete = 'Sky 16:9';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Sky2.jpeg' WHERE image_url IS NULL AND rete = 'Sky 2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyCinema.jpeg' WHERE image_url IS NULL AND rete = 'Sky Family';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyAutore.jpeg' WHERE image_url IS NULL AND rete = 'Sky Autore';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyClassic.jpeg' WHERE image_url IS NULL AND rete = 'Sky Classic';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyMania.jpeg' WHERE image_url IS NULL AND rete = 'Sky Mania';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyMax.jpeg' WHERE image_url IS NULL AND rete = 'Sky Max';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyShow.jpeg' WHERE image_url IS NULL AND rete = 'Sky Show';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyTg24.jpeg' WHERE image_url IS NULL AND rete = 'Sky TG24';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyTg24.jpeg' WHERE image_url IS NULL AND rete = 'Sky TG24 Active';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyVivo.jpeg' WHERE image_url IS NULL AND rete = 'Sky vivo';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/StudioUniversal.jpeg' WHERE image_url IS NULL AND rete = 'Studio Universal';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Telepiu.jpeg' WHERE image_url IS NULL AND rete = 'Tele+ 16:9';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Telepiu.jpeg' WHERE image_url IS NULL AND rete = 'Tele+ Bianco';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Telepiu.jpeg' WHERE image_url IS NULL AND rete = 'Tele+ Grigio';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Telepiu.jpeg' WHERE image_url IS NULL AND rete = 'Tele+ Nero';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Telecupole.jpeg' WHERE image_url IS NULL AND rete = 'Telecupole';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Tmc.jpeg' WHERE image_url IS NULL AND rete = 'TMC';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Tmc.jpeg' WHERE image_url IS NULL AND rete = 'TMC2';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Axn.jpeg' WHERE image_url IS NULL AND rete = 'AXN';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/QoobTv.jpeg' WHERE image_url IS NULL AND rete = 'Qoob';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rai4Logo2010.jpeg' WHERE image_url IS NULL AND rete = 'RAI 4';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/FantasyChannel.jpeg' WHERE image_url IS NULL AND rete = 'Fantasy Channel';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiStoriaLogo2010.jpeg' WHERE image_url IS NULL AND rete = 'Rai Storia';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiInternational.jpeg' WHERE image_url IS NULL AND rete = 'Rai International';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyUno.jpeg' WHERE image_url IS NULL AND rete = 'Sky Uno';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiMed.jpeg' WHERE image_url IS NULL AND rete = 'Rai Med';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyCinemaHits.jpeg' WHERE image_url IS NULL AND rete = 'Sky Cinema Hits';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/BabyTv.jpeg' WHERE image_url IS NULL AND rete = 'Baby Tv';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyCinema.jpeg' WHERE image_url IS NULL AND rete = 'Sky Cinema Italia';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiScuola.jpeg' WHERE image_url IS NULL AND rete = 'Rai Scuola';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/DeejayTv.jpeg' WHERE image_url IS NULL AND rete = 'Deejay Tv';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiGulp.jpeg' WHERE image_url IS NULL AND rete = 'Rai Gulp';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Boing.jpeg' WHERE image_url IS NULL AND rete = 'Boing';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Iris.jpeg' WHERE image_url IS NULL AND rete = 'Iris';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/TV2000.jpeg' WHERE image_url IS NULL AND rete = 'TV2000';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/TgNTelesubalpina.jpeg' WHERE image_url IS NULL AND rete = 'Telesubalpina';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/GRPTelevisione.jpeg' WHERE image_url IS NULL AND rete = 'GRP Televisione';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/DeAKids.jpeg' WHERE image_url IS NULL AND rete = 'DeAKids';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiMovie.jpeg' WHERE image_url IS NULL AND rete = 'Rai Movie';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/RaiExtraLogo2010.jpeg' WHERE image_url IS NULL AND rete = 'Rai Extra';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/La5.jpeg' WHERE image_url IS NULL AND rete = 'La 5';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Cielo.jpeg' WHERE image_url IS NULL AND rete = 'Cielo';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/BonsaiTV.jpeg' WHERE image_url IS NULL AND rete = 'Bonsai TV';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/Rai5.jpeg' WHERE image_url IS NULL AND rete = 'Rai 5';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/MediasetExtra.jpeg' WHERE image_url IS NULL AND rete = 'Mediaset Extra';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/La7d.jpeg' WHERE image_url IS NULL AND rete = 'La 7d';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyPassion.jpeg' WHERE image_url IS NULL AND rete = 'Sky Passion';
UPDATE archivio_items SET image_url = 'https://zotrurzfsaerabpqgjiq.supabase.co/storage/v1/object/public/archivio/reti_televisive/SkyComedy.jpeg' WHERE image_url IS NULL AND rete = 'Sky Comedy';