-- Abstract aggiornato (19/22)
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - La protesta degli studenti. Oggi 130 cortei di studenti che sono scesi in piazza per dire no alla riforma Fioroni che prevede il reinserimento degli esami di riparazione e la conferma del numero chiuso per alcune facoltà. Momenti di tensione si sono registrati a Milano e Napoli. La prossima settimana il ministro incontrerà le associazioni studentesche.' WHERE id_originale = 30663;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Stupri e violenze, orrore senza fine. Allarme a Bologna nella notte un altro stupro, in dieci giorni sono 4 le ragazze vittime della violenza. Un altro stupro una infermiera romena ha denunciato il padre che l''ha prima picchiata e poi violentata.' WHERE id_originale = 30666;
UPDATE archivio_items SET abstract = 'Una donna di 28 anni è stata uccisa, travolta da un auto, guidata da una cittadina russa, senza patente e completamente ubriaca. Il fatto è avvenuto presso Francavilla al Mare (PE) e, l''investitrice, ha cercato di fuggire dopo l''incidente, ma è stata bloccata dalla polizia municipale.' WHERE id_originale = 30693;
UPDATE archivio_items SET abstract = 'Oggi al GT si vuole parlare della propria cameretta, luogo di sogni e di giochi per ogni bambino. Testimonianza di Martina, 12 anni che ci porta a visitare la propria stanza. Tanti CD e tanti poster dei propri idoli, su tutti RHCP e Finley, ma anche (inaspettatamente) una splendida Audrey Hepburn in "Colazione da Tiffany".' WHERE id_originale = 30697;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Delitto di Meredith: la salma è arrivata a Londra. I tre presunti responsabili continuano a protestare la propria innocenza, ma nelle loro testimonianze continuano a contraddirsi. E scoppia la guerra dei loro legali che pretendono di fissare con maggiore precisione l''ora del decesso..' WHERE id_originale = 30745;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Continua la verifica degli alibi degli indagati per l''omicidio di Meredith Kircher, un video riprenderebbe Amanda che rientra in casa la sera del delitto mentre un professore svizzero confermerebbe la presenza di Patrick Lumumba nel suo locale all''ora del delitto. Allo studio anche le scarpe sequestrate a Raffaele Sollecito che però ribadisce la sua innocenza..' WHERE id_originale = 30749;
UPDATE archivio_items SET abstract = 'Amato denuncia: nell''interland milanese ragazzi minorenni sfruttano bambine per pagare i propri debiti di gioco. "Occorre fermare il fenomeno se no il nostro paese andrà in rovina". Ha aggiunto il ministro.' WHERE id_originale = 30792;
UPDATE archivio_items SET abstract = 'Ha rischiato di morire soffocato uno spacciatore del Gabon che, per sfuggire all''arresto, ha ingerito diversi ovuli di coaina. Sentendosi male sono stati gli uomini della GdF ad aiutarlo, prima e ad arrestarlo dopo. È successo nelle vie adiacenti a Porta Palazzo dove lo spaccio di droga continua senza sosta.' WHERE id_originale = 30849;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - La multinazionale del crimine. A Roma, nei pressi di Palazzo Chigi, sono stati trovati 600 milioni di $ da ripulire, frutto del traffico di droga. L''operazione, condotta dalla DIA di Roma in collaborazione con la Guardia di Finanza di Milano, ha sgominato l'' organizzazione "Made in Italy SpA. 19 le persone finite in manette, tutti mafiosi italo-canadesi..' WHERE id_originale = 30854;
UPDATE archivio_items SET abstract = 'Oggi in aula al tribunale di Torino sono state fatte vedere le immagini registrate dalla polizia durante gli scontri fra gli ultras del toro e della juve durante l''ultimo derby. La maggior parte dei fermati sono juventini, sono molto giovani e decidono di patteggiare e risarcire le forze dell''ordine con BEN 500€ di risarcimento danni.' WHERE id_originale = 30858;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Scandalo a Corte. In Inghilterra proseguono le indagini sul ricatto per un video di sesso gay in cambio di cocaina, in cui è stato coinvolto un esponente della Famiglia Reale: l''uomo è protetto da una rigorosa diffida nazionale, mentre in Italia possiamo rivelare che si tratterebbe di Linley, il primo genito della principessa Margharet.' WHERE id_originale = 30936;
UPDATE archivio_items SET abstract = 'È questione di ore poi, appena il decreto sulla sicurezza, verrà pubblicato sulla GU, tutte le prefetture del Piemonte saranno investite di poteri speciali. Quella di Torino dichiara di essere già pronta a mettere in atto la parte relativa alle espulsioni di cittadini, anche comunitari, per motivi di ordine pubblico.' WHERE id_originale = 30952;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Espulsione degli immigrati. Sulle espulsioni degli immigrati interviene anche il cardinal Tarcisio Bertone: ''Occorre distinguere tra buoni e cattivi, tra il grano e la zizzania e non fare di ogni erba un fascio, l''Italia è stato un paese di emigranti dobbiamo valorizzare la tradizione dell'' accoglienza''..' WHERE id_originale = 30969;
UPDATE archivio_items SET abstract = 'Dopo il suicidio di un 14enne, 3 studenti minorenni di un liceo di Ischia sono indagati per violenza privata, avrebbero indirizzato frasi ingiuriose contro il ragazzo..' WHERE id_originale = 30999;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Decreto espulsioni. Il presidente rumeno Basescu critica i provvedimenti sulle espulsioni presi dal governo italiano ritenendoli improvvisati e ingiusti e, dice che, Bucarest chiederà all''Unione Europea di giudicarli. Si cerca, comunque, dopo i tragici fatti di Roma di abbassare i toni e di non mandare a monte le relazioni politiche fra i due paesi.' WHERE id_originale = 31013;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Il "blocca-telefonini". Esiste un congegno che blocca il cellulare dei vicini fastidiosi: è illegale, ma negli Stati Uniti ha un grande successo. Si chiama jammer e funziona nel raggio di 10 metri permettendo di bloccare la comunicazione di quelle persone abituate ad urlare quando parlano ad un cellulare. Se solo si potesse utilizzare in treno….' WHERE id_originale = 31021;
UPDATE archivio_items SET abstract = '(sito rai) -  Sarà la versione teatrale di Gomorra, documentato best seller sui traffici della camorra di Roberto Saviano, ad aprire la puntata di domani, della rubrica teatrale del Tg3 Chiediscena. Lo spettacolo, regia di Mario Gelardi, è in scena a Napoli al teatro Mercadante. Immagini dello spettacolo che fa il tutto esaurito tutte le sere ed intervista al regista. Ospite della trasmissione Massimiliano Varrese, protagonista dello spettacolo "Tre metri sopra il cielo", anche questo tratto dall''omonimo libro best seller di Federico Moccia.' WHERE id_originale = 31059;
UPDATE archivio_items SET abstract = 'Minis. Nani a canestro 
Da oggi nelle sale il film con Dennis Rodman, il grande cestista che scende in campo con una squadra di grandi piccoli giocatori..' WHERE id_originale = 31091;
UPDATE archivio_items SET abstract = 'Il Gt è andato con un gruppo di ragazzi a vedere un film-documentario "Il viaggio di Grace". Il film, ambientato in Sudan,  parla di una ragazzina che ha dovuto fuggire a Nord per scappare dal conflitto che per 20 anni ha colpito il suo Paese. Adesso che ha 12 anni sta tornando a casa nelle sue terre. Il film può essere richiesto visitando il sito www.volint.it.' WHERE id_originale = 31572;
UPDATE archivio_items SET abstract = 'Con le parole, Fabri Fibra gioca al ritmo di rap, il suo ultimo disco lo ha intitolato "bugiardo" e, in questa intervista, sembra sincero. I suoi testi possono sembrare violenti e sempre contro qualcuno e qualcosa, ma Fabri ha le idee chiare e le esprime bene. Lui non ce l''ha con le donne, ma col sistema che porta le ragazze a mettersi in mutande all''ora di cena (vedi veline e similari), ce l''ha con quelle ragazze che, fatto il calendario nude, dicono di aver risolto tutti i loro problemi, ce l''ha con quelle persone che non dicono mai che la droga fa male (forse perché gli piace ancora). Lui ha il coraggio di dirolo, in televisione, che la droga distrugge chiunque e che, ce n''è in giro una tale quantità che nessuno può chiamarsi fuori dal problema. Insomma Fibra, finisce che ci piaci!' WHERE id_originale = 31635;
UPDATE archivio_items SET abstract = 'La giovane rock-band spiega al Gt che è meglio cantare in inglese e lavorare in provincia per non essere influenzati da tendenze del momento. Definiscono il loro rock genuino, fresco, veloce. Hanno aperto il concerto di Vasco Rossi a Milano.' WHERE id_originale = 31136;
UPDATE archivio_items SET abstract = 'Il maghetto va a ruba 
I fan di Harry Potter dalla Germania alla Cina in fila per comprare il settimo e ultimo libro della saga..' WHERE id_originale = 31161;
UPDATE archivio_items SET abstract = '"In Italia ci sono bambini che giocano a dadi e pagano i loro debiti organizzando una baby-prostituzione". E'' l''allarme lanciato dal Ministro Amato il quale continua dicendo che occorre intervenire altrimenti si condanna il nostro paese..' WHERE id_originale = 31297;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Rudy Erman Guede, quarto sospettato per l''omicidio di Meredith Kercher a Perugia, è stato catturato oggi in Germania..' WHERE id_originale = 31309;
UPDATE archivio_items SET abstract = 'Dalla community virtuale al grande pubblico. Tante band italiane partono dal sito di Myspace e diventano famose. Ne è esempio il nuovo gruppo Lost che sta diventando conosciutissimo grazie a Myspace. Un modo per cercare il successo senza avere necessariamente una casa discografica alle spalle..' WHERE id_originale = 31316;
UPDATE archivio_items SET abstract = 'Raffaele Sollecito ha chiesto di essere risentito dai magistrati per chiarire alcuni aspetti che potrebbero dimostrare la sua innocenza. Il giovane insiste ancora sul suo alibi che lo vedrebbe davanti al computer nelle ore in cui si è compiuto l''omicidio. Si allungano i tempi per l''estradizione di Rudy Guede dalla Germania..' WHERE id_originale = 31367;
UPDATE archivio_items SET abstract = 'Il punto sulle indagini sull'' assassinio di Meredith Kercher. Ora si parla della presenza di una nuova coppia sul luogo del delitto. Il caso resta in prima pagina anche in Gran Bretagna e negli USA.' WHERE id_originale = 31399;
UPDATE archivio_items SET abstract = 'Sistema economico, Mercato, Consumo, Preadolescenza, Industria, Tendenze, Immagine Iginio Straffi e le sue Winx, un caso internazionale, un successo planetario che parte dalla periferia dell''impero (mediatico), Loreto, nelle Marche, pacioso paesone noto finora solo per il santuario e, colpisce al cuore persino Disney. Economix, programma economico condotto da Myrta Merlino, dedica la puntata di oggi alla disamina di questo fenomeno industriale, che parte da un cartoon e si..' WHERE id_originale = 31453;
UPDATE archivio_items SET abstract = 'Comprate abiti e oggetti marcati Product Red. I soldi non finiranno tutti all''azienda, ma verranno in parte destinati al Global Found che si impegna nella lotta contro l''aids. In studio si mettono in palio alcune magliette della Red con la scritta Mtv.' WHERE id_originale = 31609;
UPDATE archivio_items SET abstract = '(sito digital-sat.it) - ''''Ultras nel mondo: curve infuocate'''' nelle puntate precedenti ha raccontato le tifoserie di Inghilterra, Scozia, Balcani, Olanda, Polonia, Russia, Argentina, Brasile e Turchia. Ora Danny Dyer e'' arrivato in Italia dove incontrera'' le tifoserie della Roma, della Lazio, della Juventus (dove è ancora vivo il ricordo dell''Heysel), dell''Atalanta, della Fiorentina e del Brescia. La passione del numero uno dei supporters bergamaschi, Bocia, e'' forte e viva come non mai: ''''Il calcio oggi e'' davvero uno schifo, ma la passione vera e'' ancora tramandata nelle nostre case. Noi finche'' esisteremo la porteremo avanti fino alla fine".
"Devi difendere uno striscione -spiega Bocia- ma prima di fare uno striscione devi essere gruppo''''. Danny assiste inoltre a quello che e'' considerato il miglior derby d''Europa: Roma - Lazio. Per conoscere meglio le due tifoserie decide di vedere meta'' del derby nella curva sud con i ''''Roma Ultras'''', e l''altra meta'' nella curva nord con gli ''''Irriducibili'''', i noti hooligans della Lazio. Durante la partita, Danny assiste a scontri della polizia con tifosi, fumogeni, bengala e a coreografie dei tifosi come non ne aveva mai viste altrove, ed esclama: ''''Provo una sensazione indescrivibile''''. Testimonianza del giornalista sportivo Giancarlo Galavotti.
La violenza negli stadi e i gruppi Ultras, fenomeno, purtroppo, sempre di stretta attualità, non sono di certo un male solo italiano. E’ un dato di fatto che questo rappresenti un problema serio in tutto il globo, una vera minaccia per lo sport più amato e seguito al mondo. In questo momento, quindi, è quanto mai caldo e attuale il tema affrontato nella serie di documentari “Ultras nel mondo: Curve infuocate” (Football Hooligans International) in onda su Discovery Channel. Il viaggio all’interno delle tifoserie violente cerca di scoprire la verità su questo fenomeno, andando direttamente a contatto con il mondo degli ultras: i gruppi di hooligans che portano la violenza organizzata nel “gioco più bello del mondo”. Danny Dyer, che presenta questa serie disincantata ed avvincente, ha recitato la parte di Tommy Johnson nel film del 2004 Football Factories, che racconta la storia di un giovane hooligan inglese. Ma come dice Danny, “quello era solo un film’. Ora, per il nuovo programma di Discovery channel che lo vede protagonista, Danny deve incontrare le vere tifoserie che stanno dietro le squadre di calcio, vedere le partite insieme ai membri di ciascuna tifoseria, e parlare perfino con i loro capi.
Danny, dopo aver girato la serie, ha spiegato come quest’ultima illustri “un livello completamente nuovo della violenza nel calcio”. Lo spettatore, infatti, potrà vedere scene di Danny filmato dalle telecamere in mezzo a tafferugli, sotto il lancio di gas lacrimogeni, o perfino sotto i colpi di armi da fuoco. “Ultras nel mondo: curve infuocate” racconta la storia vera della guerra sugli spalti.
Ogni episodio si occuperà di un paese diverso e dell’incidenza del fenomeno hooligans nel calcio del paese esaminato. La serie analizzerà la storia di questo fenomeno, la sua evoluzione in ciascun paese, e il ruolo delle tensioni razziali, sociali e religiose nell’escalation del problema. Mostrerà anche come, malgrado gli sforzi delle autorità per cercare di controllare il comportamento degli hooligans, vi sarà sempre una frangia di tifosi di calcio pronti a guerreggiare a qualunque costo..' WHERE id_originale = 31647;
UPDATE archivio_items SET abstract = 'I tifosi di due squadre di calcio che hanno appena finito di assistere alla partita e salgono sul metro per tornare a casa. Chi ha vinto è un po’ troppo esuberante e allora gli avversari decidono che è ora di mettere "a posto" chi è un po’ troppo esagitato. Alla fine bevono tutti  una lattina di FANTA e torna, così, la tranquillità - Claim: "Fanta, between us" - Musica: "Love Shack" dei B 52''s.' WHERE id_originale = 31771;
UPDATE archivio_items SET abstract = 'BMW SERIE 3 TOURING - Nello spot attraverso la soggettiva di un’auto in movimento delinea un percorso fatto di scritte che compongono un messaggio: “Sei raggiungibile ovunque. Sai sempre dove andare. Puoi comunicare con tutti. Hai tutte le risposte. Hai il totale controllo della tua vita. Ma sei ancora capace di perderti?” È con questo interrogativo (nel frattempo il contesto, dapprima urbano, lascia il posto a una natura sconfinata) che si chiude il filmato di matrice meditativa. Claim: Enjoy Touring. 
Musica - Come Sei Veramente - Giovanni Allevi dall''album "No Concept (2005)"
Note: Argentina la location: la capitale Buenos Aires, concentrato di architetture e culture, ha ospitato le riprese lo scorso aprile per tre giornate.' WHERE id_originale = 31778;
UPDATE archivio_items SET abstract = 'FIAT GRANDE PUNTO - Uno spot semplice semplice - pur nella raffinata realizzazione - che vuole giocare sull’impatto naturale garantito dalla forza del prodotto e sulla carica emotiva affidata alla strofa di una canzone di successo del cantante modenese: “Ho guardato dentro un’emozione e ci ho visto dentro tanto amore, che ho capito perché non si comanda al cuore. E va bene così .... Senza Parole”. 
Claim: "E'' arrivata, Punto"
Musica: Senza Parole - Vasco Rossi dall''album "Tracks (2002)"
Note: Carrè Noir ha inventato e dato vita a Mister Dot, il pittogramma del marchio che sarà proposto in decine di versioni ‘animate’.' WHERE id_originale = 31779;
UPDATE archivio_items SET abstract = 'IMMAGINI: 
la band suona sulla spiaggia. Immagini di una ragazza su uno yacht con un ragazzo, i due ragazzi litigano. Immagini della ragazza che cammina sulla spiaggia, ma alla fine la ragazza torna dal ragazzo..' WHERE id_originale = 31782;
UPDATE archivio_items SET abstract = 'IMMAGINI:
I cantanti cantano e le loro immagini appaiono in bianco e nero( formate da puntini). Immagini di uomini, un calciatore, bambini, il tramonto e l''alba del sole   formate da tasselli colorati..' WHERE id_originale = 31783;
UPDATE archivio_items SET abstract = 'Girato in una scuola, lo spot prende in considerazione un gruppo di giovani che sono al bagno e sembra stia fumando. Appena sentono aprirsi la porta buttano via quello che hanno in mano che, non sono sigarette, ma trombette di carnevale. Voce fuoricampo: "questo può sembrare stupido, tuttavia qualche volta faremmo qualsiasi cosa per assomigliare agli altri. Persino iniziare a fumare"  - Slogan: "ricordatevi c''è sempre un''alternativa. Help per una vita senza tabacco" (campagna patrocinata dai vari Ministeri della Salute europei)' WHERE id_originale = 31803;
UPDATE archivio_items SET abstract = 'In questo spot girato per Romanian National Organization of Disabled People lo spettatore è invitato a fare un''espermento: ripetere il suo nome con una striscia di scotch sulla bocca.
Messaggio "per una persona disabile questo non è un''esperimento. Puoi aiutare con una donazione".' WHERE id_originale = 31808;
UPDATE archivio_items SET abstract = 'In questo spot girato per la campagna "Pubblicità Progresso" si vede una persona anziana su un letto in ospedale mentre gioca a carte da solo quando arriva il figlio e lo abbraccia. La scena cambia e i due si ritrovano in mezzo ad un prato nella stessa situazione. Messagio: "regala un sogno ad un malato. Gli farà sicuramente bene".' WHERE id_originale = 31809;
UPDATE archivio_items SET abstract = 'In questo spot Keisha Castle-Hughes afferma: "Ciao ragazzi! L''istruzione è una cosa molto importante, che vogliate farlo o no, dovete farlo comunque. Se volete diventare degli ingegneri, dei matematici o delle attrici o degli attori, dovete  studiare. Credo che sia fondamentale che ogni bambino abbia l''opportunità di poter studiare. Capita,ed è triste, che ad alcuni bambini con talenti innati per qualche attività non sia data la possibiltà di coltivarsi attraverso l''istruzione. E'' importante che tutti possano avere accesso all''istruzzione. I nostri presidenti, i nostri ministri devono avere a cuore questo. Solo con la tua voce puoi cambiare il mondo. Solo con la tua voce puoi avere una buona istruzione. Solo con la tua voce."' WHERE id_originale = 31811;
UPDATE archivio_items SET abstract = 'In questo spot girato da Fundaciò'' Esclerosis Multiple una ragazza immobile sul divano parla della sua impossibilità di muoversi mentre il mondo intorno a lei si muove ininterrottamente. Una scritta in sovraimpressione riporta il seguente messaggio: "L''unica vera malattia paralizzante è l''indifferenza. Il 15 di agosto muovetevi per la sclerosi multipla".' WHERE id_originale = 31820;
UPDATE archivio_items SET abstract = 'Nello spot girato da Mtv Networks si vedono alcune immagini di povertà dell Africa, alcuni bambini che vanno a scuola, Gandhi, alcuni bambini che emigrano ecc. Una voce esterna commenta ricordando che una voce da sola non basta a sconfiggere la povertà nel mondo, ma se tuttti si facessero sentire sarebbe molto più facile. Messaggio: "Non abbiamo più scuse. Basta con la povertà."' WHERE id_originale = 31824;
UPDATE archivio_items SET abstract = 'SWATCH COLLEZIONE AUTUNNO-INVERNO 2005 - "Flash Mob" Tante persone (europei in un caso, asiatici nell’altro) in un momento preciso decidono di saltare, causando effetti collaterali all’altra parte del mondo. 
Musica "Cash the Trill"' WHERE id_originale = 31835;
UPDATE archivio_items SET abstract = 'SUZUKI SWIFT - Nella pubblicità un gruppo di ragazzi che giocano a calcio vengono sfidati dal guidatore della Swift. Si scoprirà che il guidatore è il fenomeno del Manchester United Cristiano Ronaldo.
Note: musica Jingle originale
Note: pubblicità in concorso con Mtv' WHERE id_originale = 31836;
UPDATE archivio_items SET abstract = 'In questo spot girato da ADEE un adolescente si sciacqua la faccia e toglie la lametta dal rasoio. L''inquadratura si sposta sul lavandino su cui inizia a gocciolare del sangue. Una scritta in sovraimpressione recita: "un giovane su cento usa la lametta prima che gli sia spuntata la barba" Una voce esterna commenta: "in Europa il suicidio è una delle principali cause di morte tra i 15 e i 24 anni. Aiutaci ad affrontare il disagio giovanile prima che sia troppo tardi".' WHERE id_originale = 31848;
UPDATE archivio_items SET abstract = 'In questa pubblicità un gruppo di persone è a tavola e sta mangiando. Con molta inciviltà rovesciano i piatti per terra, buttano il cibo e versano le bevande sul pavimento. Un gruppo di bambini entra di corsa e distrugge una pianta nel vaso. Una voce esterna commenta: " in casa vostra non vi comportereste mai così, vero? E allora perché quando andate nei prati o nei boschi vi comportate così? Ma i boschi e i prati sono casa vostra, lo capite o no?" Sullo sfondo si vede un prato pieno di spazzatura. Messaggio: "il verde è tuo: difendilo!"' WHERE id_originale = 31849;
UPDATE archivio_items SET abstract = 'In questo spot di Progetto Itaca, patrocinato da Pubblicità Progresso una donna racoonta la sua malattia che è: la depressione.' WHERE id_originale = 31869;
UPDATE archivio_items SET abstract = 'Nello spot girato da ADEE per Foundation against Cancer le immagini mostrano un prestigiatore che si esibisce in mezzo alla folla riscuotendo molto successo. Terminata la sua esibizione passa con un cappello tra la folla per raccogliere le offerte e nota una bambina con un grosso cappello sul capo che gli sorride. Lui allora la prende per mano e la porta in mezzo al cerchio formato dagli spettatori e le toglie il cappello scoprendo la testa calva a causa della chemioterapia; le cala sugli occhi il suo copricapo e lo solleva recitando una formula magica. La bambina scopre così di avere nuovamente i capelli. Messaggio: "la magia di donare".' WHERE id_originale = 31892;
UPDATE archivio_items SET abstract = 'In questo spot girato come un cartone animato un politico tiene un discorso davanti ad una sala vuota. Ad un certo punto esclama: "nessuno si è mai permesso di contraddirmi. Sono grande". All'' improvviso spunta una mano da sotto e qualcuno dice: "tu non sei grande; tu sei solo". Messaggio: "rispetta chi non la pensa come te".' WHERE id_originale = 31898;
UPDATE archivio_items SET abstract = 'In questo spot si vede un bambino che pulisce macchine in un parcheggio. Mentre sta sfregando una macchina con uno straccio prende un pastello da terra e esegue degli esercizi di matematica utilizzando i numeri delle targhe. La guardia lo scopre e gli fa delle domande. Messaggio: "incoraggia la creatività. Previeni l''emarginazione".' WHERE id_originale = 31904;
UPDATE archivio_items SET abstract = 'In questo spot girato dalla BEW&Partners un uomo interroga il colpevole di aver condannato molte persone alla pena di morte. Al termine dell''interrogatorio quest''ultimo è libero di andarsene. Una scritta in sovraimpressione recita: "conosciamo i colpevoli ma non possiamo condannarli. 58 paesi nel mondo sono ancora liberi di praticare la pena di morte"' WHERE id_originale = 31912;
UPDATE archivio_items SET abstract = 'In questo spot due persone fanno sesso via chat, scambiandosi messaggi. Nell''inquadratura finale la donna si sta fumando una sigaretta, quando arriva il marito, le chiede se è stato bello e lei risponde: "bellissimo". Messaggio: "vi siete mai chiesti se la chat condiziona i vostri rapporti?".' WHERE id_originale = 31913;
UPDATE archivio_items SET abstract = 'Nello spot viene pubblicizzata una raccolta di figurine per ricordare il papa Giovanni Paolo II°.' WHERE id_originale = 31918;
UPDATE archivio_items SET abstract = 'FIAT PUNTO STARJET - Nella pubblicità si vede sfrecciare una punto e al suo passaggio un vento impetuoso scuote il paesaggio. Quando la macchina si ferma anche il vento smette di soffiare.
Claim: Ora divertiti. Punto.
Note: musica di Vasco Rossi "Rewind"' WHERE id_originale = 31919;
UPDATE archivio_items SET abstract = 'RAI DI TUTTI DI PIU'' - In questa pubblicità una troupe della rai intervista una bambina che ha interpretato il ruolo di cappuccetto rosso in una recita come se fosse un personaggio importante.
Claim: "se è importante per te è importante per noi. Rai, di tutti, di più".' WHERE id_originale = 31923;
UPDATE archivio_items SET abstract = 'In questa pubblicità viene mostrata la sala d''attesa di un ospedale che ora dopo ora continua a riempirsi di gente che aspetta e fa la fila. Messaggio: "questa è l''Italia senza privilegi, che aspetta, fa la fila, prende il tram e può contare solo sulle proprie forze".' WHERE id_originale = 31928;
UPDATE archivio_items SET abstract = 'Un ragazzo sta guardando una pubblicità cartellonistica che reclamizza il servizio civile, una voce fuoricampo afferma: "migliaia di ragazzi hanno già scelto il servizio civile e, da oggi, anche i ragazzi possono fare la loro parte". Immagini di ragazzi che fanno volontariato con i bambini e gli anziani. Messaggio: "se hai tra i 18 e i 28 anni scegli il servizio civile perché così fai una scelata che ti cambia la vita, tua e degli altri" (spot patrocinato dalla Presidenza del Consiglio dei Ministri e dall''Ufficio Nazionale per il Servizio Civile).' WHERE id_originale = 31942;
UPDATE archivio_items SET abstract = 'Due donne sono sedute ad un tavolino di un bar e si insultano, una è molto signorile e l''altra è diabolica. Nell''attimo in cui viene stappata una bottiglietta di Aperol Soda, la voce fuori campo dice: " Aperol soda mette d''accordo le due anime dell''aperitivo"
claim: Aperol Soda, pochi gradi tanto gusto..' WHERE id_originale = 31967;
UPDATE archivio_items SET abstract = 'THE AXE EFFECT- Lo spot è girato in una grande casa della campagna inglese dove un ragazzo dandosi il deodorante non si accorge che lo stesso  finisce anche sul cavallo. A questo punto il cavallo si avvia verso le stalle dove ci sono delle bellissime cavalle molto fashion che hanno perso la testa per lui. Alla fine lui le chiama tutte per appartarsi.
Claim: The Axe Effect..' WHERE id_originale = 31972;
UPDATE archivio_items SET abstract = 'Intervento populista di Beppe Grillo alla commissione europea. In pratica l''intervento del comico riguarda la nostra politica e, in particolare, di quanti condannati e indagati ci siano nel nostro parlamento, unico al mondo. Infatti se un quartiere come Scampia ha un incidenza di pregiudicati di 1 a 15, nelle nostre Camere gli indagati e condannati sono uno ogni 10.' WHERE id_originale = 31977;
UPDATE archivio_items SET abstract = 'Due gambe bellissime stanno uscendo da un edificio. Le gambe in questione sono di Alessia Merz che, avvicinatasi all''auto di uno spasimante, con la punta della scarpa controlla i pneumatici che sono sgonfi per cui la bella Alessia dice NO e se ne va verso un''altra macchina. Anche questo ha i pneumatici sgonfi e così "ciccia". Finalmente Alessia trova un auto con le gomme a posto, così lei sale sulla vettura. Mentre il fortunato automobilista e resta di stucco per la strana fortuna capitatagli; la voce fuoricampo dice: "controlla i pneumatici, avrai solo benefici..." - (potrebbe essere preventivo, ma le marche dei prodotti sono troppo in evidenza).' WHERE id_originale = 31997;
UPDATE archivio_items SET abstract = 'DOLCE & GABBANA LIGHT BLUE PROFUMO- Nello spot un ragazzo ed una ragazza si baciano appasionatamente su un gommone in mezzo al mare( probabilmente Capri). Prima di andare oltre la scena viene fermata dal regista.
Musica    Parlami D''amore Mariù - Jorge Durian
dall''album "Alla Luce Del Sole (2004)"..' WHERE id_originale = 32010;
UPDATE archivio_items SET abstract = 'IMMAGINI:
Emily Haines entra in un supermercato e si aggira tra i vestiti , le luci si spengono all''improvviso e lei vede riflessa nella telecamera con un uomo alle spalle. Emily si gira all''improvviso e spinge l''uomo dietro di lei che è un manichino e dietro di lui ce ne sono altri che cadono uno dopo l''altro..' WHERE id_originale = 32011;
UPDATE archivio_items SET abstract = 'ESSO ENERGY E-DIESEL- Una macchina virtuale uscita da un videogame entra nella realtà solo per rifornirsi presso una stazione Esso con il nuovo energy E-diesel. SLOGAN: "Esso, un''idea più evoluta del diesel"
claim: " Esso siamo automobilisti come te" 
Musica    Run Away..' WHERE id_originale = 32019;
UPDATE archivio_items SET abstract = 'Lo spot è molto efficace sia con le immagini che con il linguaggio. Immagini in sequenza di volti di ragazzi e ragazze e poi a figure intere da soli o in compagnia o in discoteca. La voci fuoricampo, con tono imperativo, dicono: "Devi tornare prima. Devi fare presto. Devi abbassare il volume. Devi abbassare la cresta. Devi essere divertente. Devi far finta di niente. Devi essere bella. Devi essere come tua sorella. Devi metterla giù dura. Devi tirarti da paura. Devi avere i muscoli. Devi sfidare il limite. Devi avere successo. Devi fare sesso. Devi stare in pista. Devi uscire di testa. Devi bere. Devi fumare. Devi calare. DEVI SBALLARE!" pausa e poi un coro di vosi in sequenza dicono di NO! Slogan: "Il vero sballo è dire no" - Spot realizzato dal Ministero del lavoro e delle politiche sociali - Dipartimento delle politiche sociali e previdenziali.' WHERE id_originale = 32046;
UPDATE archivio_items SET abstract = '"No title" - Il velo islamico può essere fonte di discriminazione: spot della rassegna "The One Minutes" (regia di Irina Shames, Germania). Una ragazza, probabilmente turca gira per le strade di Berlino con indosso il velo, molti la guardano, ma anche lei, attraverso il velo guarda ggli altri, senza essere vista!' WHERE id_originale = 32088;
UPDATE archivio_items SET abstract = 'Un ragazzo completamente nudo corre a perdifiato su un prato seguito dal proprio cane. In testa ha il casco! (immagini forti da interpretare, ottimo).' WHERE id_originale = 32165;
UPDATE archivio_items SET abstract = 'Una giovane coppia è un po’ in crisi, lei gli telefona sul cellulare, lui non risponde perché sta guidando. Lei sta diventando paranoica e si chiede: "non mi risponde perché non mi ama più" - Lui risponde: "è perché ti amo che non ti rispondo mentre guido" - Finalmente lui arrica a casa e lei gli regala un auricolare dicendogli: "basta che rispondi!" - (potrebbe essere preventivo, ma le marche dei prodotti sono troppo in evidenza).' WHERE id_originale = 32166;
UPDATE archivio_items SET abstract = 'Lo spot  è girato al''interno di una casa dove si sta svolgendo una festa tra amici e un raggazzo crede di recevere un sms sul suo cellulare da una ragazza appena conosciuta che lo ha invitato al piano di sopra con chiari intenti sessuali. Purtroppo quegli sms li sta mandando un ragazzo che vuole farsi prendere la birra, che è al fresco, nella vasca del bagno. Claim: "hi, keeps it simple"' WHERE id_originale = 32182;
UPDATE archivio_items SET abstract = 'LE 7 PECHES CAPITAUX VUS PAR MAGNUM - L''ORGUEIL nello spot che rappresenta la vanità una signora ha appena avuto un incidente, perde sangue dal naso, ma l''unica cosa che le viene in mente di fare: è darsi il rossetto alle labbra.' WHERE id_originale = 32194;
UPDATE archivio_items SET abstract = 'MICROSOFT WINDOWS XP - Immagini animate a colori e in bianco e nero dove una ragazzina racconta la sua formazione scolastica e la conoscenzqa del computer. La ragazza tiene a confermare che le storie sono suae fantasie, ma grazie al sistema operativo windows è più facile scrivere correttamente e mettere le immagini. Voce fuoricampo: 2con microsoft windows XP, devi solo scegliere" - Claim: "your potential, our passion!" - Musica: originale di Jonathan Elias.' WHERE id_originale = 32209;
UPDATE archivio_items SET abstract = '4 uomini stanno aspettando qualcosa.. Uno è dal barbiere, uno disegna, uno è appoggiato al pick-up, uno è sull''amaca. Ad un certo punto si alza il vento e i 4 corrono verso la loro imbarcazione perché hanno un obiettivo da raggiunfere: raggiungere i 38 nodi. Naturalmente ce la fanno e, per festeggiare, si accendono una sigaretta Rothmans..' WHERE id_originale = 32223;
UPDATE archivio_items SET abstract = 'Un signore molto ben vestito sta palleggiando con qualcosa che non è un pallone. Quando l''inquadratura stringe, ci si accorge che è un pacchetto di sigarette. Il signore, a questo punto, tira un calcio fortissimo e distrugge il pacchetto e le sigarette all''interno.  (Campagna promossa da Generalitat de Catalunya - Departament de Sanitat i Seguretat Social)' WHERE id_originale = 32227;
UPDATE archivio_items SET abstract = 'Nella pubblicità una nonna riceve una chiamata registrata dalla segreteria telefonica da suo nipote che la invita a cena dato che la moglie ha preparato le fettuccine ai funghi. Ma la signora anziana non intende andare perché sta già mangiando le fettuccine ai funghi di 4 salti in padella.
Claim: 4 salti in padella findus: quelli buoni per davvero
Note: Jingle originale per Findus' WHERE id_originale = 32233;
UPDATE archivio_items SET abstract = 'Nella pubblicità tutti quelli che mangiano Fonzies si leccano le dita con un gesto seducente, compresi due ragazzi che incrociano lo sguardo e subito lo distolgono guardando in direzioni opposte.
Claim: se non ti lecchi le dita godi solo a metà
Note: musica I Wanna Kiss You - Costantini e Pizzimenti' WHERE id_originale = 32240;
UPDATE archivio_items SET abstract = 'Nella pubblicità girata da Libera viene ripreso un omicidio di Camorra. La polizia allontana i curiosi dalla scena del delitto, di cui rimane un contorno del cadavere fatto con il gesso. Una bambina riesce a eludere la sorveglianza, si avvicina al contorno di gesso, prova a cancellarlo con la mano ma non ci riesce. Viene poi inquadrata una lavagna con su scritto "la Camorra", la bambina si avvicina e cancella la scritta con la mano. Una scritta in sovraimpressione recita: aiutialmola a cancellare questa vergogna".' WHERE id_originale = 32251;
UPDATE archivio_items SET abstract = 'Nella pubblicità realizzata da Libera si vedono alcuni bambini che disegnano sull''asfalto con dei gessetti. Passano in sovraimpressione delle scritte che ci dicono che la casa è stata confiscata alla mafia. Messaggio: "e tu da che parte stai?"' WHERE id_originale = 32253;
UPDATE archivio_items SET abstract = 'In questo spot, realizzato da Libera, alcuni bambini si coprono la faccia per non vedere le immagini di un uomo morto, un ragazzo che si buca, una nave stracarica di immigrati proveniente da Tirana ecc. Lo spot mostra poi le facce dei bambini sorridenti e passa dal bianco e nero ai colori. Messaggio: "l''indifferenza è una malattia mortale"' WHERE id_originale = 32254;
UPDATE archivio_items SET abstract = 'Lo spot è stato girato da Libera. Vengono mostrate immagini di un capannone in cui la Mafia per anni ha compiuto crimini. Lo spot termina mostrando un gruppo di bambini che vi entra per giocarci. Messaggio: "da luogo di morte a luogo di vita senza dimenticare".' WHERE id_originale = 32255;
UPDATE archivio_items SET abstract = 'Nella pubblicità alcuni ragazzi alcuni ragazzi decidono di andare in un peep-show, ma anziché vedere lo spogliarello di una ragazza, dal finestrino osservano con desiderio la nuova Lancia Ypsilon.
Claim: "nuova Lancia Ypsilon Momo Design. Eccitante"
Note: musica Fortress Europe - Asian Dub Foundation' WHERE id_originale = 32258;
UPDATE archivio_items SET abstract = 'Nella pubblicità una voce commenta le difficoltà da affrontare per emergere nel mondo della musica..' WHERE id_originale = 32279;
UPDATE archivio_items SET abstract = 'In questo spot Morag Ross, make-up artist del film Aviator, commenta la sua scelta di usare il mascara Maxfactor per le sue qualità.
Claim: maxfactor, the make-up of make-up artists' WHERE id_originale = 32283;
UPDATE archivio_items SET abstract = 'GO UP - Diversi ragazzi che indossano gli occhiali Ray Ban, si elevano rispetto al mondo che li circonda.Uno sale sul cofano della macchina, un altro su un pilone, un altro su un cornicione…  Lo scopo: guardare il mondo con una prospettiva differente. Musica  Jingle Originale Per Ray Ban - Mauro Pagani
 Note:  Lo spot è ambientato a Buenos Aires e ha richiesto oltre 150 comparse. 
Claim: Change your view' WHERE id_originale = 32292;
UPDATE archivio_items SET abstract = 'QS MTV DAY - Pubblicità del quotidiano sportivo Qs. Immagine di nuotatori che si tuffano in piscina seguita dall''immagine del quotidiani Qs. Voce di fondo: " Arriva Qs, il nuovo quotidiano sportivo che darà voce a tutti gli sport". Immagine del direttore Xavier Jacobelli  - Claim: sport minore a chi?' WHERE id_originale = 32295;
UPDATE archivio_items SET abstract = 'QS MTV DAY - Pubblicità quotidiano sportivo Qs. Immagine di una squadra di Rugby che sta giocando seguita dall''immagine del quotidiano Qs. Voce di fondo:" Arriva Qs, il quotidiano sportivo che darà voce a tutti gli sport". Immagine del direttore Xavier Jacobelli. Claim: Sport minore a chi?' WHERE id_originale = 32296;
UPDATE archivio_items SET abstract = 'QS MTV DAY - Pubblicità quotidiano sportivo Qs. Immagine di un giocatore di basket seguita dall''immagine del quotidiano Qs. Voce di fondo:" arriva Qs, il nuovo quotidiano sportivo che darà voce a tutti gli sport". Immagine del direttore Xavier Jacobelli - Claim: sport minore a chi?' WHERE id_originale = 32297;
UPDATE archivio_items SET abstract = 'QS MTV DAY - Pubblicità quotidiano sportivo Qs. Immagine del quotidiano sportivo seguita dall''immagine di un atleta che pratica windsurf. Voce fuori campo: "arriva Qs, il quotidiano sportivo che darà voce a tutti gli sport" - Immagine del direttore Xavier Jacobelli - Claim: "sport minore a chi?"' WHERE id_originale = 32298;
UPDATE archivio_items SET abstract = 'SWEETY: IL PULCINO MTV DAY - Pubblicità di videosuoneria per il cellulare (servizio in abbonamento). video del pulcino Sweety che canta e balla, puoi riceverlo  sul tuo cellulare inviando un sms al numero 48277, sono disponibile anche i wallpaper del pulcino.' WHERE id_originale = 32300;
UPDATE archivio_items SET abstract = 'Per la campagna No Excuse 2015 patrocinata da Mtv è stato realizzato uno spot sulla tutela dell''ambiente. Una ragazza è al telefono con una sua amica. Naturalmente parlano del nulla. Dopodichè la stanza comincia ad allagarsi. Lei continua a parlare al telefono senza preoccuparsi di ciò che le accade intorno. Finisce per essere completamente sommersa ma continua a parlare al telefono.
Messaggio: "Se non ti occupi del mondo prima o pio il mondo si occuperà di te."' WHERE id_originale = 32303;
UPDATE archivio_items SET abstract = 'Nella pubblicità si vodono alcuni pezzi dei video dei Planet Funk tra cui si vedono immagini in cui compare un robot e altre in cui si vedono degli uomini che scaricano rifiuti da un camion.
Note: musica Stop Me - Planet Funk' WHERE id_originale = 32305;
UPDATE archivio_items SET abstract = 'SORRIDE RAI - Nella pubblicità gruppi di ragazzi muniti di bastoni appuntiti si fronteggiano in un paesaggio di periferia e sembrano bande rivali pronte a uno scontro. In realtà i ragazzi si riuniscono per raccogliere i rifiuti. Voce fuoricampo: "A volte la realtà è migliore di come la immaginiamo.."
Claim: "Sorride Rai: buone notizie, c''è una nuova tv".' WHERE id_originale = 32312;
UPDATE archivio_items SET abstract = 'RAI DI TUTTI DI PIU'' - In questa pubblicità un ragazzo viene intervistato dopo aver risposto correttamente alla domanda del professore di inglese, come se fosse una persona importante.
Claim: "se è importante per te è importante per noi. Rai, di tutti, di più".' WHERE id_originale = 32313;
UPDATE archivio_items SET abstract = 'TIM MAXXI RICARICA - Stavolta tocca a Diego sorprendere Adriana. Al suo risveglio le fa trovare 4 micini sul letto, 4 stelline, 4 paperelle, indizi che la porteranno dall''amato Diego..  Musica    I Just Wanna Live - Good Charlotte dall''album "The Chronicles Of Life & Death (2004)" - Claim: "Tim vivere senza confini".' WHERE id_originale = 32330;
UPDATE archivio_items SET abstract = 'In questo spot girato da SCHTIFTI si vede uno skateboard che lentamente si piega come sotto un grande peso. Si sente lo sgranocchiare di patatine e deglutire. Con un rutto lo skate torna alla forma originale. Messaggio: "aiutiamo i bambini a perdere peso mostrandogli quanto possa essere divertente lo skate"' WHERE id_originale = 32345;
UPDATE archivio_items SET abstract = 'In questa pubblicità viene sottolineata la contrapposizione tra l''uomo e l''animale, in particolare come l''uomo vede l''animale e viceversa. Messaggio: "la schiavitù non si è umanizzata nell''ultimo millennio"' WHERE id_originale = 32348;
UPDATE archivio_items SET abstract = 'Nella pubblicità girata dall''ADEE viene mostrata una cabina fotografica in cui una ragazza di undici anni si fotografa i genitali per vendere le foto in strada.
Messaggio: " save the children finland"' WHERE id_originale = 32349;
UPDATE archivio_items SET abstract = 'Spot realizzato da United Nations Office on Drugs and Crime che tratta il tema dello sfruttamento sessuale. Nello spot si vedono in sovraimpressione delle scritte che sono le promesse fatte alle donne per venire nei paesi ricchi. Quindi, lavoro, opportunità, soldi, felicità. Nella realtà, come ci è mostrato dalle immagini, si tratta di prostituzione, droga, violenza e sfruttamento sessuale. "Più di 700.000 donne subiscono la tratta ogni anno con lo scopo dello sfruttamento sessuale e del lavoro forzato".' WHERE id_originale = 32353;
UPDATE archivio_items SET abstract = 'IMMAGINI:
Un uomo è in una città, in mezzo alla strada con un mazzo di fiori in mano, sale su un treno e dona i fiori alla gente, nel cielo appaiono disegnati dei girasoli. Delle ragazze ballano per strada insieme ai cantanti. L''uomo fa dei  movimenti con sfere di cristallo e  una folla sta assistendo alla danza delle ragazze e dei cantanti..' WHERE id_originale = 32362;
UPDATE archivio_items SET abstract = 'RAI DI TUTTI DI PIU'' - Nella pubblicità due anziani ballano il tango e vengono intervistati da una troupe della rai come se fossero personaggi importanti.
Claim: "se è importante per te è importante per noi. Rai, di tutti, di più".' WHERE id_originale = 32366;
UPDATE archivio_items SET abstract = 'Nella pubblicità compaiono in successione degli orologi ispirati al mondo della giungla che ad ogni ora differente danno indicazioni su azioni da fare a ogni singolo animale raffigurato sul quadrante.
Claim: Always Surprising
Note musica Jingle originale..' WHERE id_originale = 32367;
UPDATE archivio_items SET abstract = 'Nella pubblicità un ragazzo ascolta la radio dal suo cellulare e ad ogni stazione radiofonica, cambia la musica e cambia taglio di capelli.
Claim: how are you?
Musiche: For lovers - Wolfman feat. Pete Doherty
                 Velocity Shift - Overseer
                 Insane In The Brain - Cypress Hill
                 Redneck Woman - Gretchen Wilson
                Who''s Got The Bacon? - Howie B
                Get Up Stand Up - Bob Marley' WHERE id_originale = 32370;