-- Abstract aggiornato (20/22)
UPDATE archivio_items SET abstract = 'E'' l''Africa il Paese verso il quale si rivolgono maggiormente le star e offrono il loro contributo. L''ultimo è stato Bono degli U2. Ma molti sono i divi che per tutto l''anno hanno saputo rispettare il loro impegno: Brad Pitt, Nicole Kidman, George Clooney. Hanno capito che dove la politica non può o vuole arrigvare, loro qualcosa di concreto lo possono fare.' WHERE id_originale = 34575;
UPDATE archivio_items SET abstract = 'Un anziano di 66 anni preso a bastonate nel milanese da due giovani rapinatori. Presi i soldi i due sono usciti dall''appartamento, ma i vicini sono riusciti a bloccarne uno. Il sedicenne, è stato arrestato. Ora è nel carcere minorile di Beccaria con l''accusa di rapina e violenza aggravata..' WHERE id_originale = 34615;
UPDATE archivio_items SET abstract = 'Ieri a Milano il ragazzo, con problemi psichici, ha colpito la donna con una bottiglia e poi le ha tagliato la gola. All''origine del gesto forse una banale lite perché lui voleva lasciare la scuola. Dopo il gesto il ragazzo è andato in treno a Brescia e lì si è costituito dicendo di aver ucciso la madre ma di non sapere perché. Domani mattina sarà sentito dal Gip.' WHERE id_originale = 34629;
UPDATE archivio_items SET abstract = '892424 MTV DAY - pubblicità del numero telefonico informativo delle pagine gialle. Immagine di un campeggio al quale Claudio Bisio partecipa ma, scontento della vacanza chiama il numero 892424 delle pagine gialle per prenotare una vacanza in un albergo. Infine è presente l''immagine di un''operatore delle pagine gialle con lo slogan: " per ogni esigenza affidati al tuo assistente personale" - Claim: "892424, con te 24 ore su 24".' WHERE id_originale = 34645;
UPDATE archivio_items SET abstract = 'Nella pubblicità un ragazzo per recuperare il pacchetto di Cipster incastrato nel distributore vi entra dentro. Nel distributore di fronte una ragazza fa la stessa cosa.
Claim: Cipster, se impazzisci per una impazzisci per tutte
Skunk Machine - Ettore Della Campa & Gianfranco Clerici' WHERE id_originale = 34647;
UPDATE archivio_items SET abstract = 'ADIDAS F50 - Nella pubblicità due ragazzi vedono correre verso di loro una marea di giocatori di calcio tutti intenti ad impossessarsi della palla. Quando la folla sembra a un passo dal travolgerli si chinano e chiudono gli occhi, scoprendo poi che in realtà sono solo tre ragazzi che corrono loro incontro con una palla tra i piedi.
Claim: impossible is nothing
Note: musica La Danza delle sciabole de Aram Khachaturian' WHERE id_originale = 34648;
UPDATE archivio_items SET abstract = 'Coprifuoco alcolico scattato alle due di questa notte: indagine a Riccione. Nei ristoranti divieti dappertutto. I gestori dei locali dicono che rispetteranno il divieto, ma sostengono che in altri paesi sono state trovate altre soluzioni, come quella del guidatore designato. L''inviato non ha visto nessun controllo.' WHERE id_originale = 34655;
UPDATE archivio_items SET abstract = 'Due nuove vittime dell'' eroina in poche ore, a Siracusa e nell''ascolano, nei giorni scorsi c''erano stati 3 morti a Roma. Probabile la presenza sul mercato di droga tagliata male..' WHERE id_originale = 34661;
UPDATE archivio_items SET abstract = 'In questo spot vengono mostrate alcune immagini della vita di una donna come se il tempo tornasse indietro. Infatti questo è il punto di forza del prodotto, l''essere in grado di rimuovere fino a dieci anni di macchie.
Claim: un'' altra idea del programma dentale AZ' WHERE id_originale = 34679;
UPDATE archivio_items SET abstract = 'I momenti di vita e di crescita di uomini e donne, da quando sono bambini,poi adolescenti, poi ragazzi ed infine genitori ed una voce in sottofondo che ribadisce come ‘loro’ (n.r.d. le marche) siano state sempre presenti in ognuna di queste situazioni, ogni volta che loro ne avevano bisogno
Claim: “Le tue marche, la tua storia” - Musica Lazy Afternoon - Dany Binia' WHERE id_originale = 34685;
UPDATE archivio_items SET abstract = 'In questa pubblicità fatta a cartone animato i due personaggi si incontrano e si innamorano a prima vista e si vedono alcune scene della loro vita ispirate a film famosi come per esempio American Beauty e Ghost.
Claim: Just Delighted.
Note: musica You''re my world - Helen Reddy' WHERE id_originale = 34690;
UPDATE archivio_items SET abstract = 'In questa pubbliciità Britney Spears e un ragazzo si guardano prima di entrare in due stanze vicine di un hotel e anche se un muro li divide provano sensazioni espresse con una successione molto rapida di immagini.
Claim: vuoi osare?' WHERE id_originale = 34691;
UPDATE archivio_items SET abstract = 'BMW SERIE 1 - Una ragazza in fila all''esterno di un cinema viene avvicinata da un coetaneo che arriva trafelato per il ritardo. Il ragazzo inizia a parlarle, ma lei ha una reazione stupita, si volta e fa per ignorarlo. Alla fine si dirige verso l''interno. Il ragazzo prova a fermarla, ma la ragazza si volta infastidita, liberandosi con un gesto rapido. Il protagonista non riesce a capire cosa stia succedendo e si sente chiamare da una voce conosciuta. E'' una ragazza, identica alla prima ma con un look diverso, che sta scendendo ora dalla sua auto.
Claim: BMW Serie 1. One like no one.
Note: Jingle originale per BMW - Ferdinando Arnò' WHERE id_originale = 34701;
UPDATE archivio_items SET abstract = 'ALFA ROMEO 159 SPORTWAGON - Nella pubblicità si vedono alcune persone che compiono gesti ritenuti folli come fare il bagno in un acquario e immergersi nel mare vestiti da sposa. Una voce esterna commenta lo svolgersi delle azioni.
Claim: "Il cuore ha sempre ragione"
Musica: Michael Andrews-Goldfish' WHERE id_originale = 34705;
UPDATE archivio_items SET abstract = 'ALFA ROMEO 159 SPORTWAGON - Nella pubblicità si vedono alcune persone che compiono gesti ritenuti folli come incendiare una cabina telefonica e dondolarsi su una gru come se fosse un''altalena. Una voce esterna commenta lo svolgersi delle azioni.
Claim: "Il cuore ha sempre ragione"
Musica: Michael Andrews-Goldfish' WHERE id_originale = 34706;
UPDATE archivio_items SET abstract = 'Nello spot si vede una ragazza. Arriva il marito brutto e in mutande. Lei lo mette in lavatrice e compare un uomo di colore molto attraente.
Claim: Coloreria italiana coloured is better..' WHERE id_originale = 34707;
UPDATE archivio_items SET abstract = 'E'' la città in assoluto più danneggiata dai graffittari. Chi realizza queste scritte contesta soprattutto la società in cui vivono. Nelle interviste i cittadini mostrano di non apprezzare le lordure sui muri. 1 ragazzo su 2 fra i 13 e i 18 anni ha usato almeno una volta una bomboletta spray. Solo a Milano 40.000 i palazzi imbrattati.' WHERE id_originale = 34766;
UPDATE archivio_items SET abstract = 'CONAD SUPERMERCATI - (Voce fuoricampo) "di vini ce ne intendiamo, ne abbiamo stappati, sorseggiati, selezionati. Adesso: provate il nostro Asti spumante DOC a soli 2,50€. Adesso provate Conad" - Le immagini invece scorrono su un tavolo imbandito pieno di cibi e di vini di ogni tipo" - Calim: "Conad, artisti nella qualità. Maestri nella convenienza" - Musica: "sotto questo cielo" di Zucchero.' WHERE id_originale = 34867;
UPDATE archivio_items SET abstract = 'Un campo di calcetto, giochi nuovi e un giardino verdissimo. 
Così alcuni ragazzi torinesi hanno progettato e realizzato interventi sulla loro scuola. Si sono improvvisati architetti e hanno cambiato il volto alla loro scuola. Torino grazie a questo e altri progetti è stata giudicata la città più attenta alle esigenze dei ragazzi.' WHERE id_originale = 34884;
UPDATE archivio_items SET abstract = 'FATTI IL CAPO - Lo spot si svolge davanti ad un bancone del bar. Una donna sensualissima ha, infilato nella giarrettiera, un punteruolo rompighiaccio (stile "basic insitnct", per intenderci) e chiede: "il capo". Il barista le porta un grosso cubo di ghiaccio che lei, col punteruolo, fa a pezzi! Claim: "Amaro del Capo, pretendetelo ghiacciato"..' WHERE id_originale = 34912;
UPDATE archivio_items SET abstract = 'OfBonollo Grappa Amarone Barrique 2006 - Nello spot possiamo vedere un uomo distinto dall''accento inglese, sembra un vero intenditore ma quando assaggia la grappa non la riconosce come tale e rimane stupito. Claim: "Grappa Ofbonollo non ha termini di paragone"..' WHERE id_originale = 34915;
UPDATE archivio_items SET abstract = 'Bruno Stefano Monchiero, 28 anni, di origini argentine, è stato arrestato per il tentato omicidio di un giovane 19enne, aggredito all''uscita da un pub in seguito ad una lite scoppiata per futili motivi di gelosia. Era stato colpito al collo da una bottiglia rotta.' WHERE id_originale = 34926;
UPDATE archivio_items SET abstract = 'Nella nuova rubrica di Loveline, Filippo Nardi si trasforma in un severo professore di educazione sessuale: come si comporteranno gli studenti interrogati? Nell''interrogazione di Filippo Nardi ha come argomenti il sesso orale e la prevenzione delle malattie.... La ragazza deve far vedere come si indossa correttamente un preservativo. Un po’ di imbarazzo c''è!..' WHERE id_originale = 34992;
UPDATE archivio_items SET abstract = 'Bici contro le auto. Un gruppo di ragazzi di Brescia progetta una pista ciclabile per la città e riesce a farla realizzare dal Comune. Andare in bicicletta per rispettare l''ambiente, mantenersi in forma, aggirare il traffico, essere indipendenti, veloci...' WHERE id_originale = 35038;
UPDATE archivio_items SET abstract = '(sito rai) - Tanti artisti differenti tra loro per origini, strumenti, esperienze uniti per suonare la musica del mondo. E’ l’Orchestra di Piazza Vittorio, una storia che nasce nel 2002 a Roma nel quartiere Esquilino per iniziativa dell’ex Avion Travel Mario Tronco, che abbiamo intervistato. Uno straordinario miscuglio multietnico di storie, umanità e suoni..' WHERE id_originale = 35183;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Lapo Elkann svela il nome di una star che gli salvò la vita rimanendogli vicina, ma con discrezione, nel momento di maggiore bisogno: si tratta dell''attrice Sharon Stone. Lei le fu molto vicina nel periodo successivo all''overdose di Lapo.' WHERE id_originale = 35216;
UPDATE archivio_items SET abstract = 'Un turista inglese si è schiantato contro una staccionata posta lungo una pista in montagna. Dopo una cena segnata da molto vino, quattro amici, tra cui l''uomo rimasto ucciso, avevano staccato i materassini di protezione lungo la pista e si erano buttati in una folle discesa. E'' successo in Val di Susa.' WHERE id_originale = 35242;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Cinque ordinanze di custodia cautelare sono state eseguite dalla polizia di Brescia nell''ambito di un''operazione contro lo sfruttamento della prostituzione di viados e il traffico di ormoni. Tre persone sarebbero ancora ricercate perché in Brasile per il carnevale. Accuse anche di cessione di stupefacenti..' WHERE id_originale = 35321;
UPDATE archivio_items SET abstract = 'Per tutti coloro che amano spedire messaggini con il cellulare c''è un avvertimento: è arrivata una nuova truffa che si manifesta con il bip di un messaggio che chiede di chiamare un numero dal telefono fisso, non sapendo però che la telefonata costerà 15 euro!!! Il gt ha provato e ha confermato questa truffa..' WHERE id_originale = 36823;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Una ragazzina cinese si getta dalla finestra della scuola, è gravvissima. Lo ha fatto perchè non ce la faceva più a vivere in uno scantinato in precarie condizioni igieniche con i familiari. Il comune sta cercando una sistemazione per la famiglia.' WHERE id_originale = 37144;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - "Adotta un disegno".E'' il titolo di una mostra di Emergency inaugurata al Vittoriano di Roma che raccoglie i disegni dei bambini ricoverati negli ospedali di Emergency nel mondo. In Iraq, Sudan, Cambogia. Una mostra itinerante che si concluderà con un''asta i cui proventi verranno devoluti ad Emergency..' WHERE id_originale = 35324;
UPDATE archivio_items SET abstract = 'C''è una svolta nell'' inchiesta: Meredith non è stata violentata, lo sostiene il medico legale che ha effettuato l''autopsia, Luca Lalli. All''inizio della vicenda, invece, sembravano non esserci dubbi.' WHERE id_originale = 35379;
UPDATE archivio_items SET abstract = 'La maggior parte dei ragazzi di oggi tente a spendere tutti i propri risparmi subito appena dopo averli ricevuti. In questi giorni, però, più di mille studenti romani hanno avuto la possibilità diu assistere a delle lezioni di economia per imparare a risparmiare e dove anche i ragazzi possono esprimere le loro opinioni a riguardo..' WHERE id_originale = 35401;
UPDATE archivio_items SET abstract = 'Oggi esce nei cinema il nuovo film di Silvio Muccino: "Parlami d''amore": un viaggio nell''amore. Silvio Muccino ha solo 25 anni ma ha già una carriera di regista, attore e scrittore e racconta al gt cosa ne pensa dei ragazzi di oggi e dell''amore e di come era lui da ragzzo: chiuso e molto fragile..' WHERE id_originale = 35421;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Una madre si è resa complice del figlio recandosi con lui di notte e sorvegliandolo mentre il ragazzo dipingeva un grande autoritratto sul muro della sua città per cercare di riconquistare la fidanzatina.' WHERE id_originale = 35440;
UPDATE archivio_items SET abstract = 'L''indagine di un gruppo di scienziati britannici ha stabilito che il film più romantico in assoluto è "Romeo + Juliet" di Baz Luhrman con Leonardo Di Caprio, seguono '' Casablanca'' , '' Via col vento'' e '' Titanic'' . La classifica è stata fatta misurando le reazioni nell''attività cerebrale.' WHERE id_originale = 35445;
UPDATE archivio_items SET abstract = 'L''orientamento negli studi: molti ragazzi delle medie inferiori sembrano scegliere scuole più tecniche, pratiche, che non teoriche. Andamento che si ha soprattutto a Torino e provincia e che inverte l''andamento dell''anno passato. Per ora i dati riguardano i due terzi dei licei piemontesi: molto in calo le iscrizioni ai licei, 21.000 le iscrizioni totali alle scuole superiori.' WHERE id_originale = 35459;
UPDATE archivio_items SET abstract = 'Pare proprio che l''apparecchio per i denti stia diventando di moda, sempre più ragazzi infatti lo portano. Può essere mobile, fisso, invisibile, evidente questo lo decide il dentista ma sta ai ragazzi la scelta del colore. C''è chi lo sceglie del colore preferito, altri della squadra del cuore...' WHERE id_originale = 35489;
UPDATE archivio_items SET abstract = 'La mafia e la camorra sono due porganizzazioni criminali molto pericolose. Alcuni ragazzi, per conto dell''iniziativa "dalla parte dei buoni", hanno intervistato Don Luigi Merula, un uomo che ha dato tutta la sua vita per la battaglia contro la camorra e che ora gira per l''Italia dicendo ai ragazzi che ognuno può fare la sua parte e che dobbiamo essere unici e non essere trascinati dagli altri..' WHERE id_originale = 35579;
UPDATE archivio_items SET abstract = 'Il bullismo si sta diffondendo sempre di più in tutte le scuole d''Italia, adesso anche tra le ragazze. L''obbiettivo è sempre quello di sentirsi più forti ma le ragazze usano come armi gli sguardi e le prese in giro. Iil gt ha intervistato alcuni ragazzi di una scuola di Ostia vicino a Roma. I ragazzi le bulle fanno minacce ma poche volte alzano le mani, inoltre, non picciono neanche ai ragazzi..' WHERE id_originale = 35580;
UPDATE archivio_items SET abstract = 'Filippo Nardi continua le lezioni di sesso sicuro nelle scuole. Oggi Filippo fa domande sul preservativo ad un gruppo di studenti della scuola media superiore. Come si indossa? Dove bisogna conservarli? I ragazzi, devo essere sincero, rispondono correttamente..' WHERE id_originale = 35643;
UPDATE archivio_items SET abstract = 'Proprio la diffusione della cocaina è da attribuire anche all''immagine che ne dà di sé lo star system, dice l''onu che chiede pene più severe. L''organizzazione non fa i nomi, ma alla mente vengono subito in mente Kate Moss, Pete Doherty, Amy Winehouse e Boy George, tanto per citarne solo alcuni..' WHERE id_originale = 35691;
UPDATE archivio_items SET abstract = 'Sono tantissimi i ragazzi che hanno contribuito alla creazione di uno spot per ricordare le vittime di tutte la mafie. Usano parole semplici però ricche di significato..' WHERE id_originale = 35710;
UPDATE archivio_items SET abstract = 'Fa discutere il progetto del Governo di concedere, dietro pagamento, l''uso delle corsie d''emergenza per lanciarsi a tutta velocità. Gli italiani in Inghilterra non si trovano particolarmente d''accordo con il progetto..' WHERE id_originale = 35713;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) -  E'' stato organizzato dalla Polizia di Stato per 3000 giovani di tutta Italia. C''erano anche gli studenti di Scampia, di "Addio pizzo" e di "Ammazzateci tutti". Il bullismo è il mafioso allo stato embrionale, affermano i ragazzi. Tra gli artisti anche Baglioni e i Negramaro e nel gran finale Fiorello e Baldini..' WHERE id_originale = 35718;
UPDATE archivio_items SET abstract = 'Intervista singola a quel "gran personaggio" di Fabrizio Corona condannato ad un anno e sei mesi per soldi falsi. Le domande riguardano le tante "cazzate" commesse dal fotografo dei vip dopo essere stato scarcerato a causa del processo soprannominato "vallettopoli". Per cui sequestro della macchina, della patente, religione, riciclaggio, soldi falsi, carcere, guadagni, Nina Moric, ecc.. ecc..ecc...' WHERE id_originale = 35724;
UPDATE archivio_items SET abstract = '(sito rai) - Gemma, una mamma di cinquant’anni, vive un’apparente tranquillità familiare al riparo delle mura domestiche. Eppure, partecipando alle vicende sentimentali della figlia, si rende conto della sua profonda frustrazione. Si accorge di non aver ricevuto quell’ascolto familiare che, nel momento della crescita, avrebbe potuto indirizzare diversamente le sue scelte esistenziali..' WHERE id_originale = 35750;
UPDATE archivio_items SET abstract = 'Alcuni ragazzi di Campalto, un paesino vicino a Venezia hanno scritto al gt per segnalare una strada molto pericolosa che passa nel loro pease vicino alla scuola e all''unica piazza dove è possibile vedersi. I ragazzi hanno già organizzato manifestazioni, raccolto firme e organizzato una biciclettata per attirare l''attenzione dei mezzi pesanti..' WHERE id_originale = 35803;
UPDATE archivio_items SET abstract = 'In Congo, Africa, migliaia di bambini non possiedono una casa o un letto dove dormire, la causa è una tremenda guerra durata 10 anni che ha fatto perdere a molti giovani la famiglia. Alcuni dicono che non avevano abbastanza soldi per la scuola e perciò sono finiti in strada, perciò l''Unicef ha aperto in Congo sette centri d''accoglienza in ciu i bambini vengono educati e cercano una famiglia..' WHERE id_originale = 35804;
UPDATE archivio_items SET abstract = 'Un Corrado Guzzanti (molto Navarro Vals) risponde alle domande di Serena Dandini. Quando lei gli chiede come mai la Chiesa continua a proibire il preservativo il Guzzanti-Vals risponde che a loro interessa il concepimento fino alla terza settimana, dopodichè ci si carica del peccato originale e "non gliene importa più niente a nessuno!"..' WHERE id_originale = 35839;
UPDATE archivio_items SET abstract = 'Come tutte le settimane Luciana Littizzetto ci porta a conoscenza di alcune notizie, apparse sui giornali, a dir poco "particolari". Questa arriva dall''Olanda dove è stata messa in commercio una birra per cani. Sembra che il migliore amico dell''uomo abbia gradito, rimane il fatto che, dice Luciana: "metà della polazione mondiale muore di fame, l''altra metà inventa minchiate!"..' WHERE id_originale = 35842;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - A 16 anni Alessandra Gangai scopre un nuovo gene umano. La ragazza racconta che inizialmente non si era quasi resa conto della sua scoperta perché non era in grado di La piccola ricercatrice è stata invitata a un convegno a Vienna per esporre la sua scoperta. La scoperta è stata fatta nei laboratori biomedici a Milano durante un concorso organizzato dall''università.' WHERE id_originale = 35875;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) -  Nell''ospedale di Desenzano è ricoverato un ragazzo milanese di 17 anni, dopo uno sballo del sabato sera in una discoteca: secondo i medici il giovane avrebbe ingerito un miscuglio di sostanze stupefacenti. Intervista ad una ragazza di 25 anni che, quando ne aveva 17, ha rischiato di morire per una pasticca, ingerita durante una serata in discoteca (Giorgia Benusiglio). Adesso la giovane si occupa di prevenzione e sostiene l''importanza di informazione che deve essere diffusa da tutto l''ambito sociale: famiglia, scuola, istituzioni..' WHERE id_originale = 35879;
UPDATE archivio_items SET abstract = '(sito rai) - Anna e Guido, due fratelli poco più che trentenni si incontrano dopo un periodo di assenza l’uno dall’altro. Ma durante la loro conversazione, Guido confida alla sorella un problema di relazione con la madre. L’anziana genitrice infatti, non si rende conto della sua eccessiva invadenza nel menage quotidiano della famiglia del figlio..' WHERE id_originale = 35887;
UPDATE archivio_items SET abstract = 'Sono più di 600 mila i ragazzi che quest''anno dovranno afrrontare l''esame di terza media. Ma c''è una novità: lo stato invierà a tutte le scuole un test che verrà proposto in tutt''Italia uguale e che verrà aperto solo la mattina in cui verrà effettuato l''esame. Per prepararsi a questa prova si può anche visitare il sito dell''istituto Invalsi..' WHERE id_originale = 36824;
UPDATE archivio_items SET abstract = '"Tutta la vita davanti". Esce nelle sale venerdì, parla dei giovani precari dei call center a cui - denuncia il film - è negato progettare il proprio futuro. Tra i protagonisti la Sabrina Ferilli, Isabella Ragonese, Elio Germano, Massimo Ghini, Valerio Mastrandrea.' WHERE id_originale = 36862;
UPDATE archivio_items SET abstract = 'E'' morto il 19enne imbottitosi di droga al rave di Segrate. Non ce l''hanno fatta a salvarlo. Quattro infarti successivi che non hanno lasciato scampo. Le testimonianze di alcune ragazze reduci dalla festa alle porte di Milano. Ci sono molti ragazzi che vanno in overdose, si aaumono cocaina, eroina, ma soprattutto droghe chimiche.' WHERE id_originale = 36902;
UPDATE archivio_items SET abstract = 'E'' morto a Roma il ragazzo di 15 anni precipitato dal tetto della scuola dove cercava di entrare. Altri due ragazzi erano con lui e dopo di lui sono caduti, quando un lucernario in plexiglas presente sul tetto della scuola non ha retto il loro peso e si è spezzato. Doveva solo essere una bravata, si è trasformata in tragedia.' WHERE id_originale = 36954;
UPDATE archivio_items SET abstract = '(sito rai) - Isabelle e’ una designer belga: disegna e progetta lampade e allestimenti luminosi. Usando materiali semplici: carta, ceramica, vetro. Subito dopo la laurea in architettura ha vinto un concorso per giovani designer. Oggi espone le sue creazioni in musei e gallerie d’arte. 
Isabelle Farahnick – designer “Da artista posso dire che e’ molto difficile vivere della propria arte in Belgio. Bisogna trovare un altro mestiere, sia come assistente o come insegnante a scuola  o un lavoretto la sera.  Per i giovani che cominciano una carriera artistica e’ molto difficile perché  non c’e’ aiuto, e’ molto duro in questo ambito riuscire a cavarsela da soli”
Come Isabelle, anche gli studenti che incontriamo all’università di Bruxelles, confermano le difficoltà per i giovani. A partire dalli costi della formazione. Secondo i dati dell’Ocse, l’organizzazione per la cooperazione e lo sviluppo, la situazione in Belgio non e’ rosea: il tasso di disoccupazione nella fascia d’età dai 15 ai 24 anni e’ del 20%, invariato nell’ultimo decennio.
Ragazza “Non e’ che vada granchè ! Non fanno molto per i giovani.  Si hanno tante speranze, però…Mia sorella e’ uscita di casa, ha avuto il sussidio di disoccupazione prima di trovare qualcosa….e tutte le sue amiche hanno fatto lo stesso”

Ragazza “Per mantenermi lavoro come cameriera”

Ragazza  “E’ proprio difficile trovare un impiego, soprattutto se non si hanno competenze specifiche. Anche se hai fatto studi qualificati per avere più occasioni, una volta usciti dall’università il lavoro non e’ certo assicurato comunque…. “

Ragazza “Dipende molto dai settori…penso che materie scientifiche tipo chimica o altro, e’ più facile…e’ più facile, si…ma io, per esempio studio psicologia…e in psicologia e’ molto difficile… Perché  c’e’ troppa gente…e’ molto difficile”

Matteo Allalouf, docente universitario di sociologia del lavoro all’università di Bruxelles conferma le forti difficoltà per i giovani. Che si affacciano su un mercato sempre più flessibile e incerto.

Matteo Allalouf – docente di Sociologia del Lavoro, Università di Bruxelles “La visione dei giovani e’ molto pessimista, soprattutto nel sud del paese, dove le possibilità di trovare lavoro per i giovani sono di molto  inferiori che nel nord del paese. La ragione principale per la quale c’e’ tanto pessimismo, direi una visione così nera del mercato del lavoro, e’ che non si riesce a guardare al futuro, a immaginarsi in prospettiva un matrimonio, dei figli, un avvenire…E’  qui che si ha la difficoltà maggiore e non tanto nell’accedere ad un impiego perché  alla fine ci si arriva ad averlo”

Anche il sistema di sicurezza sociale fino a qualche anno fa molto generoso, sta cambiando. In Belgio il 90% dei giovani studenti con in mano un diploma di scuola superiore o di laurea riceve una indennità di disoccupazione che varia a seconda dell’età, delle esperienze lavorative se ci sono state e della situazione familiare. Il problema e’ che non e’ sufficiente.

Matteo Allalouf - “In questo periodo di crisi, l’ammontare medio delle indennità di disoccupazione e’ cambiato: prima era del 45/50% dello stipendio mentre adesso queste indennità sono scese al 20/30% dei salari.. Ciò significa che il livello dei sussidi si e’ molto abbassato, per i giovani in particolare, sono troppo bassi e non permettono l’indipendenza economica dai genitori, di andare a vivere da soli… hanno sempre bisogno di essere sostenuti solo per poter sopravvivere nella nostra società.”.' WHERE id_originale = 36958;
UPDATE archivio_items SET abstract = 'A Palermo il supermercato della legalità. I negozianti si oppongono al pizzo: la tassa che i mafiosi pretendono in cambio di protezione perciò hanno organizzato una grande manifestazione per dire basta alla mafia e al pizzo..' WHERE id_originale = 37006;
UPDATE archivio_items SET abstract = 'Spazzatura uguale Napoli: è un messaggio che fa male anche ai bambini come è successo ad un ragazzo di Treviso che veniva preso in giro e picchiato perché aveva la madre di origine napoletana, lo chiamavano "monnezza" ma appena lo si è venuto a sapere se ne parlava su tutti i giornali locali e si cominciava a pensare se davvero la spazzatura influenzava la nostra idea dei napoletani..' WHERE id_originale = 37009;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - In Florida un gruppo di ragazzine, tra i 14 e i 16 anni, ha massacrato una ragazza con il solo scopo di diventare famose mettendo il filmato su internet: la ragazza è finita in ospedale con un trauma cranico, ma le sue carnefici sono state arrestate.' WHERE id_originale = 37077;
UPDATE archivio_items SET abstract = 'A Genova un bambino di 12 anni è in coma dopo essersi sparato un colpo, probabilmente per errore, con una vecchia pistola del padre. Probabilmete voleva solo giocare e credeva che l''arma, regolarmente registrata, fosse inoffensiva. Resta però ancora da chiarire la vicenda perché pare che il bossolo del colpo sia stato trovato in una stanza diversa da dove si trovava il bambino.' WHERE id_originale = 37086;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - La Polizia nella notte ha sgominato una banda di spacciatori di cocaina che regolava il traffico nel quartiere Prenestino di Roma: 21 le persone in manette, il più giovane ha 17 anni, il più grande 31. Gli agenti li hanno seguiti e filmati per mesi prima di intervenire, osservandone l''organizzazione molto efficiente. Sono statwe sequestrate 4000 dosi di cocaina.' WHERE id_originale = 37093;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Un pluripregiudicato di 43 anni, algerino è stato arrestato mentre stuprava un minorenne disabile in una galleria a due passi dalla stazione centrale di Milano. L''uomo con precedenti per rissa, spaccio, furto, aggressioni, era già stato due volte in carcere..' WHERE id_originale = 37095;
UPDATE archivio_items SET abstract = '(VOCE SU IMMAGINI) - Artisti di tutto il mondo e stelle della musica a Johannesburg per il concerto organizzato dal Presidente Sudafricano Nelson Mandela in occasione della giornata mondiale per la lotta all''aids. Presenti anche Peter Gabriel e Annie Lennox.' WHERE id_originale = 37120;
UPDATE archivio_items SET abstract = 'Il punto e virgola viene sempre usato di meno dai ragazzi, infatti viene utilizzato principalmente negli sms al posto dell''occhiolino. Molti ragazzi che sono stati intervistati dal gt non lo usano perché è poco pratico in confronto alla virgola che è più veloce. Indica una pausa nel discorso, un po'' più lunga della virgola, ma meno del punto..' WHERE id_originale = 37126;
UPDATE archivio_items SET abstract = 'Il Trio Medusa incontra Anna Ciriani altrimenti detta: "Madame Web", la prof hard. L''insegnante, come tutti ricordano, era finita in internet con un video non da educanda. Il ministro dell''istruzione l''aveva sospesa e, tuttora, è in attesa di un suo reinserimento in istituto. Visto che ciò non sta avvenendo, l''ardita prof ha deciso di chiamare le Iene per far conoscere il suo punto di vista..' WHERE id_originale = 37185;
UPDATE archivio_items SET abstract = 'In questi giorni ci sono stati molti incidenti sulle nostre strade dove anche delle persone hanno perso la vita. Contro la pirateria sulla strada è stato fatto da Music Box  e dal ministero delle politiche giovanili un documentario intitolato "La vita non è un optional" . La prima cosa che può trasformare un normale automobilista in un pirata della strada è l''alcool..' WHERE id_originale = 37203;
UPDATE archivio_items SET abstract = 'Il cantante Nicolò Fabi ama molto parlare con i ragazzi soprattutto sulla legalità. L''ha fatto in un teatro di Roma perché pensa che il rifiuo dell''illegalità e la lotta alla mafia partano sempre dai più piccoli e ad ascoltarlo c''erano tantissimi ragazzi tra cui alcuni siciliani che tutti i giorni lottano per la legalità anche grazie alla loro organizzazione "Addiopizzo"..' WHERE id_originale = 37205;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Arrestati il direttore sanitario e il titolare del centro, somministravano farmaci botulinici illegali. Le accuse sono associazione a delinquere finalizzata alla detenzione e commercializzazione di farmaci guasti o imperfetti e privi di autorizzazioni per la messa in commercio, ed esercizio abusivo della professione medica.' WHERE id_originale = 37288;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Due coniugi marocchini residenti a Milano coinvolti in un vasto traffico di stupefacenti. L''uomo è stato arrestato mentre la donna è stata denunciata a piede libero poiché in avanzato stato di gravidanza. Vendevano hashish per quantità non inferiori al kg alla volta..' WHERE id_originale = 37298;
UPDATE archivio_items SET abstract = 'Molti ragazzi usano internet, che può essere molto divertente, grazie ai giochi, si possono conoscere nuovi amici, ma anche fare brutti incontri, per questo una mamma olandese ha sfidato perfino Bill Gates padre dalla  Microsoft inventando un prgramma che aiuta a nn andare nelle strade più pericolose. Tuttavioa esistono già dei siti protetti come ad esempio easy4..' WHERE id_originale = 37340;
UPDATE archivio_items SET abstract = 'Come tutti gli anni Tavagnasco (TO) propone il proprio festival rock. Luca Bringhen parla dei 19 anni di passione, di lavoro e di volontari che hanno fatto questo raduno sempre più grande e più famoso. Quest''anno insieme ad Elio e le Storie Tese erano presenti anche Giuliano Palma e i Bluebeaters, Roy Paci e tanti altri..' WHERE id_originale = 37473;
UPDATE archivio_items SET abstract = 'Anche a tavola arriva la carta della birra con gli abbinamenti più giusti. Presentazione del volume "A tavola con la birra". 50 piatti più cucinati affiacanti a 8 tipi di birra. Qualche esempio riportato da un editore del "Gambero Rosso".' WHERE id_originale = 37492;
UPDATE archivio_items SET abstract = 'Durante la puntata di "Linea Blu" passa in sovraimpressione la scritta: "oggi e domani in 250 piazze italiane i volontari della fondazione ''aiutare i bambini'' offriranno un cappello di babbo natale, in cambio di un piccolo contributo. I fondi raccolti saranno destinati alla costruzione di un centro di accoglienza in India per bambini sieropositivi. Per informazioni www.aiutareibambini.it"..' WHERE id_originale = 37499;
UPDATE archivio_items SET abstract = 'Sono sempre di più in italia i ragazzi delle superiori che ogni anno devono recuperare dei debiti e perciò ricorrono a corsi di recupero. Ma come funzionano? Il gt è andato a vedere in una scuola vicino a Milano dove sono già stati organizzati corsi di recupero gratuiti frequentati da tantissimi ragazzi. Ma la fine dell''anno è ancora abbastanza lontana e i corsi potrebbero non bastare..' WHERE id_originale = 37502;
UPDATE archivio_items SET abstract = 'Ci sono dei ragazzi di Roma che per raggiungere la loro scuola sono costretti ad attraversare una strada senza strisce pedonali, rischiando, ogni giorno di essere investiti. I bambini testimoniano che di mattina le macchine non si fermano per farli passare, ma c''è anche qualcuno che lo fa e nota pure lui che i pedoni fanno fatica ad attraversare..' WHERE id_originale = 37503;
UPDATE archivio_items SET abstract = 'Il dibattito sui compiti a casa va avanti, ormai da molto tempo ma ora dall''Inghilterra i professori sono d''accordo coi ragazzi e stabiliscono che i compiti rendono infelici i bambini che oltretutto hanno anche il diritto di divertirsi. Intanto in Italia i ragazzi si lamentano su questo argomento..' WHERE id_originale = 37504;
UPDATE archivio_items SET abstract = 'Ormai quasi tutti sanno cos''è il cibo spazzatura: quel cibo troppo ricco di grassi e zuccheri che purtroppo piace tanto ai ragazzi. Solo in Italia sono molti i bambini a rischio obesità perciò alcuni ragazzi partecipantio al concorso "Qoco" sono stati invitati ad una lezione sul mangiare sano..' WHERE id_originale = 37505;
UPDATE archivio_items SET abstract = '(sito rai) - E’ altissima la percentuale di detenuti stranieri nelle nostre carceri. Siamo entrati in quello di Padova per parlare con albanesi, croati, rumeni che rinunciano all’ora d’aria per far parte della redazione di un giornale scritto e on line dal titolo Ristretti Orizzonti. Abbiamo intervistato la direttrice di Ristretti Orizzonti, Ornella Favero..' WHERE id_originale = 37521;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - In centinaia hanno occupato simbolicamente i gradini davanti il Ministero dell''Istruzione; a Roma gli insegnanti hanno protestato contro gli ultimi provvedimenti dell'' ex ministro Fioroni, hanno chiesto di bloccare il taglio degli organici, di ritirare l''ordinanza sui corsi di recupero, di fermare i test per la valutazione degli istituti.' WHERE id_originale = 38349;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - A Palermo proseguono le indagini sulla vicenda che ha colpito il cardiochirurgo pediatrico Carlo Marcelletti: il medico è sotto inchiesta per truffa, peculato e detenzione di materiale pedopornografico e la Procura di Palermo chiede l''arresto di Marcelletti per paura di un eventuale inquinamento delle prove..' WHERE id_originale = 38367;
UPDATE archivio_items SET abstract = 'L''associazione Italia-bianconera da sempre aiuta i bambini malati a trovare le giuste cure anche fuori dal nostro paese. Presenti alla cena di beneficenza molti calciatori della Juventus da Nedved a Buffon, da Del Piero a Pessotto. Organizzatore della serata l''ormai defenestrato da qualsiasi carica nel gruppo: Lapo Elkann che non manca mai di fare affeermazioni a dir poco ardite..' WHERE id_originale = 38373;
UPDATE archivio_items SET abstract = 'Il neo governo dovrà subito occuparsi anche di scuola visto che ormai sui debiti formativi è caos. Dopo 13 anni il ragazzo con debiti dovrà ripresentarsi a settembre davanti ad una commissione per l''esame di riparazione. Mancano però i fondi e l''organico per i corsi di recupero estivi.' WHERE id_originale = 38390;
UPDATE archivio_items SET abstract = 'Minorenni costrette a prostituirsi di notte sulle strade di Torino. Di giorno chiuse in una casa con tanti letti, una prigione da cui era impossibile uscire. Maltrattate, ingannate con un''offerta di un lavoro onesto ma ben pagato qui in Italia. Arrivavano soprattutto da Bucarest. Comprate e rivendute come schiave fino a quando sono arrivati i carabinieri a liberarle.' WHERE id_originale = 38446;
UPDATE archivio_items SET abstract = '(sito rai) - Milano, Università Bicocca, mille studenti stranieri su 30 mila iscritti. E 300 giovani da tutta Europa che nell’ateneo frequentano l’Erasmus, preparano tesi di laurea o studiano nei dottorati di ricerca.   
Abbiamo chiesto loro come si trovano in Italia, cosa apprezzano e le difficoltà incontrate. Emerge  il ritratto di un paese accogliente ma non troppo. 
Silvia è di Bratislava, in Slovacchia.      
Neli è bulgara. Studia giurisprudenza a Gerona in Spagna ed è a Milano per l’Erasmus.  
Celine è francese di Aix en Provence.  
Altro capitolo importante, come si studia in Italia. L’università è promossa, ma si cerca maggior severità come dice Robert, polacco di Danzica, che frequenta un dottorato di ricerca in medicina molecolare    
Javier, di Grenada, nonostante la provenienza mediterranea proprio non sopporta il peggior vizio italiano.    
Gentian, albanese di Durazzo, frequenta un master e giudica lo studio troppo teorico.    
Critiche che non annullano il fascino dell’Italia. Gli studenti, nonostante tutto, sceglierebbero ancora il bel paese.  E molti ammettono di prepararsi per restare..' WHERE id_originale = 38484;
UPDATE archivio_items SET abstract = 'In amicizia con alcuni calciatori dell''Inter: parla il sarto che in un''inchiesta effettuata a Milano è coinvolto in un traffico di stupefacenti. Un passato già segnato da una condanna per concorso in omicidio e ricettazione. Nelle conversazioni con i giocatori non pare però emergere nulla di penalmente condannabile. L''uomo, Domenico Brescia, si dichiara estraneo alla vicenda..' WHERE id_originale = 38503;
UPDATE archivio_items SET abstract = '(sito rai) - Calo demografico, paesi spopolati, ma non a Gorgoglione. Qui, sulle colline della provincia di Matera, gli immigrati albanesi e romeni sono cittadini come gli altri. Lavorano nell’industria della pietra, si sono integrati e stanno aiutando la piccola città a rinascere. Siamo andati a conoscerli..' WHERE id_originale = 38507;
UPDATE archivio_items SET abstract = '(spot realizzato per il WAD 2007 da MTV e staying-alive.org)
Nato nel 1975 dal celebre Julio e dalla giornalista ispano-filippina Isabel Preysler, Enrique Iglesias è testimonial di questa campagna di informazione per la lotta all''aids.
EI: ''ciao, sono Enrique Iglesias, visita il nuovo sito di staying alive su www.staying-alive.org'' (l''artista è seduto e passano stilizzate delle bollicine e un''ape che si avvicina ad un fiore. Lo sfondo è un tendaggio blu).' WHERE id_originale = 38571;
UPDATE archivio_items SET abstract = 'Gli accordi per la vendita di droga erano presi durante l''intervallo e coinvolti sono molti ragazzi (alcuni minorenni) che, come si diceva una volta: ''di buona famiglia''. Le sostanze smerciate in questi istituti supeiori di Trevisio erano prevalentemente cocaina, hascisc, ecstasy e anfetamine. Organizzazione smantellata dalle forze dell''ordine che stanno ancora adesso facendo arresti e perquisizio..' WHERE id_originale = 38589;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - La"Emanuela Setti Carraro" di Milano, scuola elementare, media e liceo statale ma con lezioni di musica e sport e tantissime altre attività. L''unica pecca della scuola può essere considerata la netta predominanza delle ragazze tra gli iscritti.' WHERE id_originale = 38629;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - A Treviso una ragazza di 13 anni, mentre tornava a casa dal catechismo con la sua bicicletta, è stata aggredita e violentata da un liberiano clandestino di 36 anni: la città è sotto choch, nella zona si sono verificati tre violenze sessuali negli ultimi giorni.' WHERE id_originale = 38630;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Per futili motivi, forse il furto di un cellulare, è rimasto accoltellato un attore del film di Harry Potter, la vittima era un giovane attore emergente: è l''ennesimo omicidio tra adolescenti in Inghilterra, dall''inizio della scuola 40 ragazzini uccisi, 14 dei quali minorenni. Baby gang armate che consumano alcol e droga, un fenomeno incontrollabile..' WHERE id_originale = 38690;
UPDATE archivio_items SET abstract = 'BOSS PURE - Una cascata d''acqua. Un uomo dal fisico scolpito che la guarda intensamente prima di attraversarla tuffandocisi dentro. L''immagine si allarga e ci rivela che tutto ciò avviene dentro la bottiglia del nuovo profumo targato Hugo Boss.
Una voce profonda recita : “Boss Pure. The new fragance, from Boss”.
Il testimonial dello spot è il modello Chris Austad..' WHERE id_originale = 38804;
UPDATE archivio_items SET abstract = 'LA SCARPA CHE RESPIRA 2008 - Durante una sfilata di moda una modella rompe un tacco. La ragazza si toglie la scarpa per continuare a sfilare, ma l''effetto è devastante: tutti i presenti svengono di colpo a causa del cattivo odore. La modella rimane, sola e stupita, in piedi sulla passerella. Una voce over ci invita a "passare a Geox, la scarpa che respira"..' WHERE id_originale = 38809;
UPDATE archivio_items SET abstract = '(sito centrodiascolto.it) - Scoperto un bunker alla periferia di Foggia usato come centrale di spaccio della droga e un laboratorio per la raffinazione della droga, soprattutto cocaina. Dieci le persone arrestate, tra queste anche un esponente di spicco della mala foggiana. I malviventi nascondevano la droga sotterrandola nei vigneti e negli uliveti del terreno circostante.' WHERE id_originale = 38846;
UPDATE archivio_items SET abstract = 'Anche oggi il conduttore di screensaver, Federico Taddia consiglia un libro ai ragazzi del gt e lo nasconde in giro per l''Italia. Oggi propone "Heike continua a respirare": la storia di una bambina che vive nel dopoguerra e che, a causa della guerra perde la madre, il padre e la  migliore amica..' WHERE id_originale = 38877;
UPDATE archivio_items SET abstract = 'Secondo Legambiente il nostro pianeta subisce più di 83 reati al giorno da parte delle ecomafie, organizzazioni criminali che usano l''ambinte per cioncludere i loro affari. Per questi alcuni ragazzi siciliani ha deciso di impegnarsi a difendere la legalità partendio proprio dall''acqua che a Vittori (Ragusa) è a rischio di inquinamento..' WHERE id_originale = 38882;
UPDATE archivio_items SET abstract = 'La violenza alle donne, sono molti i fatti di cronaca che ci parlano di questo argomento. Alcuni ragazzi della sicilia hanno railizzato dei video- spot per dire basta alla violenza. Il video parla di una ragazza che mentre tornava a casa hanno cercato di aggredire. I ragazi hanno voluto raccontare semplicemente quello che potrebbe accadere ad ognuno di noi..' WHERE id_originale = 38883;