-- Abstract aggiornato (13/22)
UPDATE archivio_items SET abstract = 'I Mattafix sono gli autori del successo degli ultimi mesi: "Big city life", tratto dal cd "Sings of a struggle", cioè "segni di una lotta". I due giovani inglesi, interpreti del nuovo Urban Soul, hanno conquistato le classifiche internazionali, si sono incontrati a Londra, dove sono nati, ma ognuno di loro porta con se contaminazioni diverse: la famiglia di Preetésh è indiana, mentre la mamma di Marlon è nata ai Caraibi..' WHERE id_originale = 8641;
UPDATE archivio_items SET abstract = '(Sito Rai 3) Il primo lungometraggio di de Oliveira. Sullo sfondo della citta'' di Oporto, negli anni ''40, la rivalitá fra due bambini compagni di classe. (Film Tv) Siamo nella città portoghese di Oporto, negli anni Quaranta. Qui, agli estremi margini dell''Europa ma come accade in tutto il mondo, due gruppi di ragazzi, compagni di classe, danno vita a numerose bande, un po'' come accade nel romanzo "I ragazzi della via Paal". Anche qui le bande si affrontano, si scontrano e mettono in gioco la loro rivalità. Così i ragazzi crescono e imparano la legge della vita. RECENSIONE: Film sull''infanzia, ma anche sul senso della vita, che prende il titolo da una formula usata dai bambini nei loro giochi. È il film con il quale il regista portoghese Manoel de Oliveira ha esordito dietro la macchina da presa ed è considerato un ottimo esempio di realismo poetico.' WHERE id_originale = 8674;
UPDATE archivio_items SET abstract = 'Durante il programma vengono trasmessi i video di Elisa, Jojo e Anastacia, ma non completi. "Most Wanted: tutto quello che i ragazzi vogliono". Un gruppo di ragazzi, guidati dal presentatore Francesco, dibatte, scherza e analizza gli argomenti che stanno più a cuore ai giovani: musica, amicizia, amore, tempo libero e storie personali raccontate in diretta o proposte attraverso e-mail, sms e telefonate. Notizia del giorno: "Gli adolescenti guardano sempre di più i film porno e il fenomeno coinvolge anche le ragazze". Altro argomento della puntata l''interculturalità. Carlo, 28 anni (18 dei quali passati in Gemania) racconta la sua esperienza e la sua integrazione con una diversa cultura. In studio, Boris è stato negli U.S.A. grazie a Intercultura, un''associazione senza scopo di lucro che organizza scambi internazionali fra studenti, e spiega come è riuscito ad ottenere l''ambito premio "King of the School". Video di Elisa "Together". Al telefono Roberta, che si è trasferita da poco a Roma, vorrebbe contattare una sua amica cagliaritana per ringraziarla di esserle stata vicino in un momento difficile della sua vita. La redazione chiama la ragazza e mette in contatto le due amiche. Video di Jojo "Leave". I ragazzi in studio parlano delle loro amicizie, in particolare di quelle lontane. Molti sms degli ascoltatori sull''argomento "porno, adolescenti e ragazze". Al telefono Alessio vuole scusarsi con Alessia per il modo in cui la tratta, esprimerle il suo affetto e convincerla a lasciare il ragazzo per mettersi con lui; la cosa però non andrà a buon fine. Video di Anastacia "Sick and tired". Alba, 18 anni, vive in America e commenta, con dispiacere, i risultati delle elezioni politiche.' WHERE id_originale = 8675;
UPDATE archivio_items SET abstract = 'Le ragazze parlano dei loro rapporti con i ragazzi. Discutono su come, spesso, i partners non riescono a capire coso vogliono da loro le ragazze, in alcuni casi si pretende solo un bacio o un rapporto fisico, mordi e fuggi,
in altri si ricerca il sentimento e la discussione. Parla una ragazza argentina sulle differenze tra i ragazzi italiani e sudamericani. Poi si tratta il "problema" del matrimonio o delle convivenze e delle storie d''amore che finiscono o iniziano. In poche parole rapporti uomo-donna.' WHERE id_originale = 8677;
UPDATE archivio_items SET abstract = 'Anche in Italia ci sono Hackers in azione, gli Hackers per quei pochissimi che ancora non lo sapessero sono i pirati informatici, a Catania è stata sgominata una banda che violava siti istituzionali, tra loro ci sono anche minorenni, e per la prima volta è stato contestato il reato di associazione a delinquere.' WHERE id_originale = 8690;
UPDATE archivio_items SET abstract = '(Sito Rai) Apple continua con la sua rivoluzione, iniziata negli anni ''70 con Apple II, e proseguita con l''introduzione di Macintosh.
Fino a ieri le più recenti innovazioni Apple si chiamavano sistema operativo Mac OS X, le applicazioni iLife, la linea di player musicali iPod, il negozio di musica on-line iTune. E oggi? Nel corso del recente MacWorld Expo di San Francisco, Steve Jobs, al grido di "piccolo è bello", ha indicato il nuovo futuro della Mela. Mac in miniatura, microbi tecnologici dotati di memoria flash, nuovi aggiornamenti dei software, prezzi accessibili a tutti. Detto fatto, ecco Mac mini, il più compatto ed economico Mac di sempre.
Alto appena 5 centimetri, con un peso di soli 1,3 chili, prezzo base 499 euro. Basta attaccare monitor, tastiera e mouse per ottenere un Mac incredibilmente compatto. Inoltre è dotato di iLife ''05, l''ultima versione dell''innovativa suite Apple per la gestione di fotografie e musica digitale, editing di filmati e creazione di musica. Ma il futuro si chiamerà anche iPod shuffle, un innovativo lettore di musica digitale basato sulla leggendaria funzionalità shuffle, che permette agli utenti di ascoltare la propria musica in un milione di modi diversi. Si interfaccia perfettamente con iTunes e con la nuova funzionalità AutoFill, che sceglie automaticamente dalla libreria musicale del computer dell''utente il numero esatto di canzoni per riempire iPod shuffle. Più piccolo e leggero di un pacchetto di gomme da masticare, è disponibile nella versione da 512 Mb e da 1 Gb, capace di contenere fino a 240 canzoni.
Anche in questo caso filosofia dell''abbattimento dei costi rispettata: 99 euro la versione base. Infine, in arrivo il pacchetto iWork 05, il software pensato per aiutare gli utenti a creare, presentare e pubblicare documenti e presentazioni con un aspetto professionale mai visto prima.' WHERE id_originale = 8692;
UPDATE archivio_items SET abstract = '(Sito Rai) Una terapia contro l''aids sarebbe anche efficace per prevenire il cancro.
E'' la conclusione di uno studio realizzato a Lione dallo Iarc, l''Agenzia internazionale per la ricerca sul cancro.
Sotto osservazione 7.300 pazienti svizzeri trattati con un cocktail di farmaci comunemente chamato "haart", acronimo inglese che sta per "terapia ad alta attività antiretrovirale".
Serve, oltre al controllo dell''evoluzione del virus hiv, anche ad aiutare a prevenire polmoniti e altre infezioni facilitate dalla sindrome.
Tra i malati di aids trattati con la "haart" il numero di casi di "sarcoma di Kaposi" e "linfoma non-Hodgkin" risultano molto più bassi rispetto agli altri malati di aids.
Secondo lo studio, pubblicato sul "Journal of National Cancer Institute", analoga "prevenzione" può riguardare anche altre forme tumorali.' WHERE id_originale = 8698;
UPDATE archivio_items SET abstract = '(Sito Rai) Bambini sempre più obesi e attività sportiva in calo tra i giovanissimi.
Non è un luogo comune, e i dati sono confermati da numerose ricerche condotte in diverse parti d''Italia.
Una delle più autorevoli porta la firma dell''Istituto di medicina dello sport di Torino, che dal 1981 ad oggi ha effettuato uno screening di massa che ha coinvolto 180.000 studenti di prima media.
Con quali risultati.

(intervista Piero Astegiano, medico dello sport)

Tradotto in cifre, significa che se nel 1991 gli obesi erano il 4,5% tra i maschi e il 5,5 tra le femmine, queste percentuali sono lievitate rispettivamente al 15,5 e al 14,5%.
I ragazzi in sovrappeso, che erano il 35% 15 anni fa, sono aumentati di un ulteriore 5%.
Dati che si accompagnano a una riduzione dell''attività agonistica, scesa nei maschi dal 50% del 1991 al 35% attuale, e nelle femmine dal 20 al 6%.
Nell''invertire questa tendenza un ruolo potrebbe essere giocato dalla scuola, ma a precise condizioni.

(intervista Piero Astegiano, medico dello sport)

Una direzione verso la quale sono orientati tutti i paesi europei.
Ne va della salute della popolazione, ma anche dei risultati delle nostre nazionali.
Numeri di questo genere ci condannano tra l''altro a un inesorabile declino sportivo.' WHERE id_originale = 8699;
UPDATE archivio_items SET abstract = '(Sito Rai) E'' l''aids l''altro tsunami, un''onda nera che travolge gran parte del mondo povero, con due killer alleati: farmaci che mancano e povertà che esclude dalle cure buona parte del terzo mondo. L''immagine dello tsunami è servita al presidente francese Chirac per lanciare alla grande - e agli altri grandi riuniti al Forum di Davos - una proposta: tassare le transizioni finanziarie internazionali, i biglietti aerei e altre operazioni di business per tentare una globalizzazione virtuosa, quella della solidarietà vera, immediata. Vorrebbe dire acquisti di cocktail di farmaci per 10 miliardi di dollari. Ma che cosa è la triterapia: è un cocktail di antiretrovirali in grado di rallentare fortemente l''avanzata del virus nel sangue. Il primo antiretrovirale di questa famiglia fu l''Azt: fermava l''infezione ma comportava gravi controindicazioni. Gli antiretrovirali sono diventati una famiglia, e più tollerati dall''organismo. E nei paesi industrializzati hanno rallentato la progressione dell''hiv.
Triterapia però vuol anche dire prezzi alti, che la rendono inaccessibile al mondo dei miserabili. "Unaids" - il presidio Onu contro l''epidemia - lavora duro per diffondere il cocktail di farmaci dei ricchi. Con qualche risultato: nel 2004 700.000 malati di aids son stati trattati. Una goccia nel mare: 6 milioni di malati urgentemente ne hanno bisogno. E diritto.' WHERE id_originale = 8700;
UPDATE archivio_items SET abstract = 'erie: EABF
Codice episodio: EABF19
Titolo episodio: IL PANZOSO E IL PELOSO
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 30/11/2003 Riassunto: Dopo un ennesimo regalo per la Festa Della Mamma fallito, HOMER porta i bambini allo Sprawl-Mart e finisce col comprare una Cucina Carnival per MARGE. HOMER usa il Carnival per creare un uomo caramellato commestibile, ma alla fine MARGE lo obbliga a portarlo alla discarica di Springfield – dove viene prontamente attaccato da un orso. Quando i Mass Media lo definiscono un codardo, HOMER costruisce una tuta combatti-orso, e dopo qualche prova di buffonerie stile Jackass, si prepara ad affrontare l’orso.' WHERE id_originale = 8712;
UPDATE archivio_items SET abstract = 'Serie: FABF
Codice episodio: FABF07
Titolo episodio: MILHOUSE NON VIVE PIÙ QUI
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 15/02/2004. Durante una gita scolastica al Museo della televisione, Milhouse mostra agli altri di aver sviluppato un nuovo tipo di atteggiamento secondo cui semplicemente non gli importa più di nulla. Intanto il sig. Burns ha trasferito Homer, Lenny e Carl in una nuova località (il bar di Boe), così non rovineranno la visita del consiglio direttivo della centrale nucleare. Apu e Manjula fanno una sosta da Boe per celebrare il loro anniversario, e Homer si rende conto che non ha preso un regalo per il suo anniversario di matrimonio con Marge. Homer si ubriaca e si ritrova a ballare per la strada, dove la gente, pensando che Homer sia un barbone, inizia a fargli delle offerte. Milhouse rivela il suo segreto: il suo nuovo atteggiamento deriva dal fatto che lui e sua madre si trasferiranno a Capitol City, dove inizieranno una nuova vita. Sia Bart che Kirk Van Houten dovranno imparare ad adattarsi ad una vita senza Milhouse in giro. Bart cerca di abituarsi ad un mondo senza Milhouse, e dopo una visita a Milhouse a Capitol City si rende conto che l''amico è cambiato per avere nuovi amici e che niente sarà più come prima. Nel frattempo, Homer ha iniziato a chiedere l''elemosina come secondo lavoro quando si rende conto che in questo modo può farsi un po'' di soldi per comprare a Marge un costoso regalo di anniversario come un paio di orecchini di diamanti. Con Milhouse fuori dalla sua vita, Bart si ritrova a legare di più con sua sorella Lisa e quest''ultima si gode il ritrovato rapporto col fratello, rapporto che viene messo alla prova quando Kirk ottiene "per pietà" la custodia del figlio Milhouse e Marge viene informata dai barboni sulla seconda fonte di reddito di Homer. Alla fine Milhouse torna ad essere il miglior amico di Bart, ma il ragazzo ha sempre un posto nel suo cuore per la sorella Lisa.' WHERE id_originale = 8713;
UPDATE archivio_items SET abstract = 'Ospite in studio Enrico Ruggeri.0.01.10. SI PARLA DI BRIGATE ROSSE, alcune immagini di repertorio dei telegiornali, l''assasinio di Emilio Rossa, l''intervista fatta a Sabina Rossa, la dichiarazione fatta da Berlinguer durante una manifestazione del partito comunista, dove lui si dissocia dalle azioni commesse dai terroristi, il racconto di quei giorni fatta da un dirigente dell''Italsider, alcune immagini del processo e le foto del corpo trovato dalle forze dell''ordine dopo l''esecuzione compiuta dalle brigate rosse. Si ritorna in studio dove si commentano le immagini viste, e Enrico Ruggeri dichiara quanto, a suo parere, questi fatti interessano i giovani, ese si interessano dei fatti di cronaca del passato, e gli critici rammentano come hanno vissuto quei momenti, e comunicano le loro opinione sui fatti e su come fu gestita la situazione. 0.04.51.55 FESTIVAL DI SANREMO.Vengono mostrate alcune immagini del festival, poi si torna in studio per commentare le varie critiche fatte dai giornali nei giorni di programmazione del festival, critiche come al solito pesanti e disfattiste, Errico Ruggeri da la sua opinione sul festival, ammette la sua utilità in ambito promozzionale di un cantante,  ovviamente bisogna saperla sfruttare, invece i vari critici in studio sono contrari e le opinioni sono diverse a secondo di chi interviene.' WHERE id_originale = 8715;
UPDATE archivio_items SET abstract = '0.01.49 AMERICAN IDIOT
0.05.49 JESUS OF SUBURBIA
0.15.20 HOLIDAY
0.19.27 BOULEVARD OF BROKEN DREAMS
0.23.47 ARE WE THE WAITING
0.26.45 LONG VIEW
0.30.59 BASKET CASE
0.34.09 WAKE ME UP WHEN SEPTEMBER ENDS
0.38.57 I FOUGHT THE LAW
0.41.47 MINORITY' WHERE id_originale = 8720;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Da un''idea nata a Firenze solo 3 anni fa, e subito adottata a Parigi, la biblioteca multimediale interattiva Passe-Livre è fondata sulla realizzazione di totem di raccolta e libero scambio di libri.
  Grazie all''associazione di volontariato "Compagni di viaggio", fondata da Fabrizio Capuano, e alla ferma volontà di un oncologo napoletano, la prima postazione in Italia è stata realizzata a Napoli nelle corsie di un reparto oncologico.

(interviste
dr. Alfredo Marinelli, day hospital di oncologia, policlinico "Federico II", Napoli
dr. Vincenzo Montesarchio, unità di oncologia azienda ospedaliera "Cotugno", Napoli)

L''iniziativa, inserita nel più ampio programma di umanizzazione della medicina, ha come obiettivo quello di mettere in Rete un valore, ma richiede il coinvolgimento di più soggetti: istituzioni, semplici cittadini, pazienti e volontari.' WHERE id_originale = 8725;
UPDATE archivio_items SET abstract = 'Erika, Katia, Carolina, Carmen, Ilaria, Serena, Letizia, Patrick, Bruno, Tommaso, Robert, Domenico, Renato, Ascanio, questi i nomi dei partecipanti della 4a edizione del Grande Fratello. Avvenimenti salienti di questa puntata sono : l''eliminazione di uno dei concorrenti, avvenuta tramite il voto di alcuni partecipanti; l''incontro tra padre e figlia all''interno della casa (la ragazza era all''oscura della partecvipazione del padre). La prima a lasciare la casa è Carmen, votata in modo casuale, del resto è entrata anche lei stasera come tutti gli altri. Per quanto riguarda Domenico ed Ilaria (padre e figlia) la situazione è un pò piu complessa. Ilaria vive da diverso tempo con il suo ragazzo, con gran disappunto del padre che non ha mai accettato questo legame. Questo ha causato la rottura del loro rapporto, infatti è da diverso tempo che non si vedono, il loro è un rapporto di amore e odio. Domenico ha accettato la richiesta fatta dagli organizzatori che gli imponevano di non far sapere alla figlia la sua partecipazione al reality. Quando è avvenuto l''ingresso di Domenico nella casa Ilaria ha mostrato molta preoccupazione e perplessità, nonostante le rassicurazioni del padre di non interferire in nessun modo nei suoi riguardi. A fine puntata fanno ingresso nella casa Renato ed Ascanio. Qui, al termine della prima settimana di permanenza, i due saranno soggetti ad una votazione che servirà a decidere l''eliminazione di uno dei due concorrenti.' WHERE id_originale = 8731;
UPDATE archivio_items SET abstract = '"Tutti al supermercato":la madre si reca a scuola a prendere il figlio piu piccolo, e come al solito non manca qualche inprevisto, di seguito si reca a prendere le altre due figli nelle rispettive scuole per poi recarsi afare spesa al supermercato. Qua comincia l''avventura, la figlia maggiore si reca subito dal ragazzo del banco della verdura, la madre deve portaqre la bambina in bagno, allora la madre affida l''altro figlio alla piu grande. La figlia presa dal commesso non si preoccupa del fratello e così il carrello del figlio continua la sua corsa,  viene visto dalla madre che esce dal bagno con la figlia, si danno all''inseguimento e una volta raggiunto tutti insieme vano alla cassa per pagare, quando fanno per uscire suona il rilevatore, la guardia del supermercato arriva e si rende conto che il suono è provocato dall''incarto della tavoletta di cioccolato che ha mangiato il figlio, per mostrare alla famiglia come funziona il rilevatore fa passare la carta davanti e lo fa suonare, il figlio vedendo il funzionamento solleva lo zaino pieno di dolciumi sopra la testa così non suona, in fine tutti vanno via non accorgendosi del furto commesso dal piu piccolo. "Finalmente domenica": è domenica la mamma sta dormendo ma arrivano i figli piu piccoli con pianola e tamburelli a fare rumore per attirare la sua attenzione, la madre vuole dormire allora mette i bambini davanti alla televisione a vedere i cartoni animati, fa per mettersi a letto quando suona il telefono, come al solito comincia la ricerca del ricevitore che naturalmente è in camera della figlia piu grande, e la telefonata e per lei. Prova a tornare a letto ma il volume della TV è troppo alto, quindi si alza e collega le cuffie al TV e le fa indossare ai figli, ci riprova va  a letto ma suonqano alla pota, sono i nonni chesi fermano a pranzo. La domenica sta per finire, risultato i nonni che si addormentano davanti alla TV, i figli si addormentano sul divano, la mamma invece è in cucina a lavare i piatti,  stremata dalla mattinata incomincia ad addormentarsi impiedi fino a crollare perterra usando la spugna come cuscino.' WHERE id_originale = 8732;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Internet e l''Africa si son dati appuntamento in questo inizio secolo.
Un appuntamento al quale l''antico continente si presenta con il ritardo di chi deve inventarsi da zero reti e infrastrutture di comunicazione. (newsfromafrica.org)' WHERE id_originale = 8735;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) 15 mamme e un papà, genitori anche di un sito che fa della genitorialità un luogo di domande e non di certezze.
Sono sparsi lungo tutto lo stivale, si sono conosciuti in una community, e quando il loro sito ha chiuso hanno deciso di creare uno spazio di confronto, lavorando a distanza, giorno e notte.
Da metà gennaio on-line, genitori che ha parti informative, come quella sulle leggi attuali in materia di maternità, paternità, adozioni, coppie di fatto, e una parte aperta a tutti i contributi.
Tra i progetti, la nascita di una vera e propria associazione.' WHERE id_originale = 8736;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Gianmarco Elia da 10 anni divide la sua vita tra l''Africa e Milano.
Attraverso l''associazione Amani for Africa cerca insieme ad altri volontari, e soprattutto agli stessi africani, di garantire ai bambini che hanno perso tutto una nuova possibilità nella vita: una casa, un tetto sotto cui ripararsi,
  quel patrimonio affettivo senza il quale ogni bambino, in ogni parte del mondo, si sentirà spezzato, abbandonato, perduto.
Amani apre case di accoglienza in Africa e cerca soprattutto di restituire agli africani il pallino del loro destino.
Il sito Internet è di importanza fondamentale per promuovere i progetti, per raccogliere adesioni, ma soprattutto per restituire un ruolo da protagonisti ai cittadini africani.
Dal sito amaniforafrica.org è infatti nato un altro progetto, non meno interessante.
Oggi è anche possibile sostenere i progetti di Amani attraverso un evento, il Giro d''Italia di corsa in alta quota e il Raid multisport, organizzati dall''associazione Sportchallengers e dalla Federazione sport in altitudine.
Un modo per restare sempre in contatto con chi lavora e soffre molto lontano dai nostri sguardi.
Un modo per comunicare, perché la comunicazione è il vero dramma aggiuntivo del continente africano.' WHERE id_originale = 8737;
UPDATE archivio_items SET abstract = 'Appena oltre Torino, la porta della speranza per chi si è trovato addosso l'' AIDS e non sapeva più dove bussare, è sempre aperta, non vogliamo sapere quello che hai fatto, ma chi sei, così c''è scritto, e così 80 persone che fanno fatica, hanno avuto amici ed un tetto quando fuori, non li voleva più nessuno: tossicodipendenti, gay, ma anche papà e mamme che hanno scoperto di aver incontrato l'' AIDS. Una casa dove molti hanno riavuto la vita, Francesco si è ritrovato padre, Mike ora ha un lavoro, Vanni ha capito che ogni giorno merita di essere vissuto, altri 50 purtroppo non c''è l''hanno fatta; l''idea di queste stanze è stata inseguita per tanto tempo, nel ''90 non era così semplice trovare un posto senza sollevare polemiche e proteste per i malati di AIDS. Così il cardinale e la Caritas che volevano un porto per i malati, hanno girato tanto, alla fine l''hanno trovato: via Moncalieri a Grugliasco, poche stanze, semplici, colorate, gli angoli per leggere, per curarsi, per cominciare a ricostruire vite spezzate, stanze che ora non bastano più, cresceranno, ma ci vogliono soldi. "Giobbe" e i suoi tanti amici, tutti volontari, ci provano, in fondo inseguono un sogno, un sogno possibile.' WHERE id_originale = 8744;
UPDATE archivio_items SET abstract = 'Ora si sa che Federico il quindicenne che ieri sera ha ucciso il padre e la madre a Roma era un ragazzo difficile, malato e che il raptus omicida è scattato proprio dopo una lite con i genitori che avevano deciso di farlo curare. Lo hanno interrogato e lui ha confermato: "Li ho uccisi perché volevano rinchiudermi in una casa di cura"; Federico, un ragazzo di 15 anni, che ieri sera,  dopo aver ucciso i genitori si è barricato armato sul terrazzo di un palazzo di sei piani nel quartiere Esquilino a Roma, oggi è stato trasferito nel carcere minorile di Casal del Marmo.' WHERE id_originale = 8758;
UPDATE archivio_items SET abstract = '(Dal sito) Il terzo documentario sui giovani con HIV/AIDS nel mondo. Presentato da P. Diddy. Kontar, USA Washington, DC, USA: Kontar ha contratto il virus dell''HIV nel corso di un rapporto occasionale con uno "che non sembrava avere l''HIV". Ora è diventato un attivista volontario in due organizzazioni per la lotta all''AIDS e parla della necessità di educare le persone sui rischi dell''AIDS, di qualunque orientamento sessuale esse siano. John, Sweden Stoccolma, Svezia: John ha contratto l''HIV facendo sesso non protetto nel corso di una "vacanza selvaggia". Consapevole del fatto che non essersi protetto è responsabilità solo sua, racconta di quanto si sente fortunato a vivere in un paese nel quale i sieropositivi possono usufruire di un''eccellente assistenza medica. Maria Victoria, Argentina
Buenos Aires, Argentina: la 25enne Maria Victoria lavora per un''organizzazione locale che si occupa di AIDS. Nel momento in cui il rapporto col suo ragazzo comincia a farsi più serio, i due discutono dei comportamenti a rischio tenuti in passato e vanno insieme a fare il test dell''HIV. Nonostante entrambi risultino essere sieronegativi, Maria Victoria sottolinea che a proteggere dall''HIV non è la fiducia, bensì il preservativo. Kefiloe, South Africa Snake Park, South Africa: la 19enne Kefiloe ha perduto la madre e il fratello per colpa dell''AIDS. Lavora per loveLIFE, il più grande programma di prevenzione dell''HIV del Sud Africa, e racconta ai bambini la sua esperienza e i rischi dell''HIV. Jaffer, India
Goa, India: il 22enne Jaffer ha contratto l''HIV all''età di 17 anni. Nonostante la sua famiglia lo sostenga pienamente, Jaffer non parla ai suoi amici del fatto che è sieropositivo: insieme ai suoi parenti racconta quanta ignoranza e discriminazione ha incontrato il giorno in cui gli hanno diagnosticato l''infezione, e quanto la sua vita sarebbe difficile se la sua condizione fosse conosciuta. Shaynon, Australia Perth, Australia: il 15enne Shaynon è risultato positivo al test dell''HIV quando aveva 1 anno. Sua madre non sapeva di essere sieropositiva e lui ha contratto il virus nel corso della gestazione. Ora vive con i genitori adottivi e si considera un ragazzo normale, uno che semplicemente prende un sacco di medicine. Leap Srey, Cambodia Phnom Penh, Cambogia: Leap Srey ha poco più di 20 anni, ha contratto l''HIV da suo marito e iconsapevolmente l''ha trasmesso a sua figlia. Suo marito e la figlia di 3 anni sono morti. Leap Srey sa che presto farà la stessa fine, perché non può procurarsi medicine.' WHERE id_originale = 8776;
UPDATE archivio_items SET abstract = 'Ai bambini che soffrono e sono costretti a lunghi periodi di degenza in ospedlale. Per alleviare il loro dolore: musica, clown, piccoli animali e...dottori amici. In parecchi ospedali Italiani hanno aderito all''inizziativa associazione clawn, questo vede alcuni ragazzi prodigarsi al loro meglio per attenuare la sofferenza dei bambini costretti a degenze in ospedale, fanno giochi, intrattenimenti, piccoli spettacoli comici, tutto quello che serve a sviare il pensiero del bambino dalla sofferenza, è un dato di fatto che facilita il lavoro del medico che trova un pazziente piu rilassato. Un''altra inizziativa è la pet terapi, o terapia con il supporto di animali, anche i cani aiutono i bambini a rasserenarsi e svagarsi e renderli piu allegri.' WHERE id_originale = 8802;
UPDATE archivio_items SET abstract = 'DVD DIFETTOSO. Un soft horror per bambini, in cui il diavolo appare nell''armadio di una soffitta. Un gruppo di ragazzini, stufi di giocare a palla, improvvissano una seduta spiritica…Per far spaventare gli amichetti, una di loro nasconde il fratellino in un armadio….' WHERE id_originale = 8807;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Promuovere l''integrazione delle persone diversamente abili nelle scuole, nel lavoro e nella società attraverso l''uso delle tecnologie ict.
E'' lo scopo del "progetto Me Too, rete telematica per la infoinclusione", presentato nel corso di Smau Menti@contatto 2005, finanziato dalla Regione Campania e messo a punto da 7 scuole di Afragola, nelle quali sono stati installati e resi operativi 8 
  laboratori informatici attrezzati in modo specifico per gli alunni meno fortunati.
"Abbiamo a disposizione vari dispositivi che consentono la fruizione delle tecnologie informatiche sia hardware che software ai disabili" dice Alberto D''Auria, consulente informatico del "progetto Me Too". "Ad esempio abbiamo tastiere speciali che possono essere attivate direttamente con il tocco, completamente programmabili. Abbiamo poi schermi a tocco, dispositivi di puntamento particolari con sensori speciali per simulare le funzioni del mouse. Stampanti Braille, display Braille, con una tavoletta che legge le righe dello schermo grazie ad un software particolare, con la possibilità di sentire anche la voce sintetizzata elettronicamente, fino ad arrivare a sofisticati monitor che facilitano la visione a chi ha disabilità di tipo visivo".
Afragola regina dell''infoinclusione, dunque, ovvero dell''inclusione delle persone diversamente abili nell''utilizzo dell''information technology.
E il web diventa sempre più luogo privilegiato di incontro e interrelazioni senza barriere.' WHERE id_originale = 8818;
UPDATE archivio_items SET abstract = '(Sito Rai). - 4° Puntata: "ASSOCIAZIONE AIN KARIM"
Non è possibile pensare che una mamma in attesa del proprio bambino sia lasciata sola, abbandonata su di una strada, costretta a prostituirsi. 
Nella nostra cultura una mamma col pancione è il simbolo della dolcezza e in ognuno di noi, vedendola, nasce un senso di protezione e amore.
Non è sempre così, non è così per tante donne che, senza l’aiuto di Paola Lamartina, non sarebbero nemmeno in grado di dare la vita al loro bambino. Aiutare queste donne a vivere la loro vita e la vita dei loro figli in maniera dignitosa è ciò che Paola intende per amore. Questa associazione gestisce a Roma due case accoglienza per nuclei familiari: madre-bambino. La storia che oggi Alessandra ci vuole raccontare è la difficoltà di diventare madre. Sono molti gli operatori e i volontari che lavorano nelle due case, che spendono il proprio tempo con i bambini per dare loro quella serenità minacciata. Molte ragazze accolte qui vengono da storie difficili, ma questa casa le sta aiutando a ritrovare fiducia e speranza. La cosa bella è che molte delle volontarie che danno la propria disponibilità sono donne e ragazze straniere.' WHERE id_originale = 8828;
UPDATE archivio_items SET abstract = 'Fame e malnutrizione sono violazioni del diritto umano fondamentale che è quello di nutrirsi, eppure ogni anno 6 milioni di bambini nel mondo muoiono di fame e malnutrizione, lo dice il rapporto 2005 della FAO, la maggior parte di questi bambini muore di malattie infettive curabili: come la diarrea, la malaria, il morbillo; che potrebbero essere superate se i piccoli avessero una costituzione fisica e un sistema immunitario sano, non indeboliti dalla fame e dalla malnutrizione. Rapporto FAO 2005, stima: 2000-2002: 852 milioni le persone sottoalimentate, di questi 814 milioni nei paesi in via di sviluppo; il 33% vive nell''Africa sub-sahariana, il 16% nell''Asia e nel Pacifico, il 75% circa delle popolazioni affamate e povere vive nelle zone rurali.' WHERE id_originale = 8833;
UPDATE archivio_items SET abstract = 'Piero Pelù, Lorenzo Jovanotti,  i Negrita, Irene Grandi e tanti altri, insieme per una versione inedita del: "Il mio nome è mai più", una canzone del ''99, cui i proventi erano destinati ad Emergency, questa volta hanno cantato per testimoniare contro la guerra e la pena di morte; un concerto promosso dalla regione Toscana per ricordare che proprio il 30 novembre 1786, il Gran Ducato fu il primo stato sovrano al mondo a cancellare dal proprio ordinamento la tortura e la pena capitale.' WHERE id_originale = 8847;
UPDATE archivio_items SET abstract = 'Si è appena concluso il consiglio dei ministri, che ha deciso fra l''altro di assumere e rendere stabili 40.000 persone comprese tra il personale docente e il personale tecnico amministrativo della scuola, tra il 2005 e il 2006, lo ha annunciato il ministro dell''istruzione Letizia Moratti.' WHERE id_originale = 8857;
UPDATE archivio_items SET abstract = 'Concetta: "Io penso che il virus colpisca sia uomini che donne in egual misura, però le donne, ad esempio nel rapporto con il loro partner sono un po'' più svantaggiate perché a volte l''uomo, prende un po'' come mancanza di fiducia il fatto che la donna chieda a lui di indossare il preservativo, oppure comunque di fare il test dell'' HIV, e quindi penso che le donne, in un certo senso siano un po'' più svantaggiate." 
Quasi il 50% delle persone affette da HIV nel mondo sono donne. 
Nell'' Africa sub sahariana raggiungono il 57%.
Tre quarti dei malati tra i 15 e i 24 anni sono ragazze.' WHERE id_originale = 8867;
UPDATE archivio_items SET abstract = '(Sito Rai)  Cos''è la felicità pensare a se stessi o donare agli altri. E ancora. Essere felici è una colpa? E'' per forza qualcosa che possiamo raggiungere solo a scapito degli altri? E quando il dilemma si dibatte tra la gioia per una promozione tanto attesa e una gravidanza inaspettata che rimescola le carte della nostra carriera? Che fare se non possiamo contare sulla persona che amiamo, sul conforto di un sostegno affettivo che ci dia la serenità di scegliere?' WHERE id_originale = 8870;
UPDATE archivio_items SET abstract = 'Un marocchino ha accoltellato la moglie italiana e l''ha buttata giù dal balcone di casa, perché lei voleva lavorare e vivere all''italiana, Antonella Trovato 22 anni, ha riportato ferite e fratture guaribili in 90 giorni, Mohammed Idhaf di 26 anni, venditore ambulante è stato arrestato dagli agenti della mobile; l''episodio è accaduto la notte scorsa in un alloggio al primo piano in via Abbiella a Torino, ed è stato l''epilogo dell''ennesimo litigio fra i 2, durante il diverbio Idhaf con un coltello ha colpito più volte la donna poi l''ha buttata giù dal balcone, prima di fuggire è sceso in strada e l''ha ancora presa a calci.' WHERE id_originale = 8876;
UPDATE archivio_items SET abstract = 'I soldati americani morti in Iraq sono arrivati in questi giorni a quota 2000, un horror esplosivo squisitamente politico di Joe Dante con: "Coming", li fa uscire dalle bare come zombie per dire: "ci hanno ucciso per una bugia", e per votare alle presidenziali contro i repubblicani; in anteprima mondiale al Torino Film Festival, il film è stato accolto da un''ovazione di 10 minuti. Tra gli altri registi dell''horror anche John Carpenter e Dario Argento.' WHERE id_originale = 8879;
UPDATE archivio_items SET abstract = 'Migliorano le condizioni di Nicola, il ragazzo di 16 anni che si è risvegliato dopo 18 mesi di coma, oggi ha ricevuto anche gli auguri della sua squadra del cuore, il grande MILAN, e del suo idolo, il pallone d''oro, il miglior attaccante al mondo: SHEVA!' WHERE id_originale = 8883;
UPDATE archivio_items SET abstract = 'Dovrebbero costituirsi domani in questura ad Asti due dei ricercati dell''operazione: "happy night", la grande retata che ha scoperchiato ad Asti un mondo di convivenza tra delinquenza e vip locali per il consumo della cocaina, uno dei due: Oreste Brignolo, 41 anni, dirigente industriale, si trova attualmente per lavoro in Germania, ma dovrebbe appunto costituirsi domani; a Cuneo in carcere stamattina è stato sentito Gippi Crosetti, gestore del bar Ligure ad Asti, principale inquisito insieme ad Urbano Andrea Carlotto, molti degli indagati saranno segnalati alla prefettura di Asti, e privati della patente.' WHERE id_originale = 8911;
UPDATE archivio_items SET abstract = 'A Parigi alle 10 di questa mattina è scattato il divieto di manifestazione e assembramenti, a rischio per l''ordine pubblico, questa è la risposta delle autorità alle violenze che sono comunque continuate per tutta la notte in numerose città francesi.' WHERE id_originale = 8914;
UPDATE archivio_items SET abstract = 'Sono tanti, cento quelli fermati nel 2005, portati in comunità sono scappati, alcuni un''ora dopo, i baby pusher a Torino vivono in piazza Vittorio, a ridosso del Po, sono marocchini e rumeni, ci sono ogni giorno, verso sera, sono nascosti tra le auto, alzano la testa, osservano, tornano a nascondersi, velocissimi si avvicinano e ripetono: "vuoi fumo?", ma hanno anche cocaina, come abilissimi giocolieri si passano le dosi, e non appena avvertono l''arrivo dei carabinieri, si dividono, alcuni fuggono lungo il fiume, ai Murazzi, altri si infilano nelle fogne e si disperdono nel groviglio di cunicoli e gallerie della Torino storica, passando da una cantina all''altra, sono fantasmi inafferrabili, il comune ha aperto una casa per loro, ma solo uno su tre accatta d''entrarvi, gli altri preferiscono la strada.' WHERE id_originale = 8916;
UPDATE archivio_items SET abstract = 'Nove persone finite in manette per traffico di sostanze stupefacenti, e grazie ad una bambina di appena dieci anni: è partita da lei la segnalazione che ha dato il via alle indagini, su un foglietto bianco la denuncia in forma anonima consegnata al commissario, al termine di una lezione di legalità in una scuola media di Trapani: "Aiuta il papà della mia amica" aveva scritto la bambina, "è un tossicodipendente, usa la droga anche davanti a lei, la compra da un certo Tano, nel quartiere San Giuliano di Trapani".' WHERE id_originale = 8917;
UPDATE archivio_items SET abstract = 'Peggio di una guerra, con 7.000 morti all''anno, 18 al giorno, una contabilità drammatica, e stiamo parlando degli incidenti stradali; oggi in tutta Europa una domenica per riflettere, ricordare, pensare. "Questa giornata" ha detto Ciampi "rafforza la memoria delle vittime e contribuisce alla rinnovata coscienza civile e al rispetto per la vita".' WHERE id_originale = 8926;
UPDATE archivio_items SET abstract = 'Ad Israele un volontario Italiano della comunita di don Benzi è stato ferito a colpi di fucile. Questo è il modo in cui protestano alcuni coloni dell''insediamento di Maon in Cisgiordania, per l''aiuto che i volontari danno ad alcuni pastori Palestinesi da tempo vittime di numerosi attacchi. 
In Iran nella provincia di Buscer si è verificata un esplosione, alcuni sospetti  erano attribbuiti a un attentato, ma in realta si è trattato di un incidente avvenuto nel cantiere della nuova digha.' WHERE id_originale = 8933;
UPDATE archivio_items SET abstract = 'Serie: 7F
Codice episodio: 7F10
Titolo episodio: BART È INVESTITO DA UN''AUTO
Stagione numero: 2
Anno di produzione: 1990/1991
Prima messa onda in Tv (USA): 10/01/1991
Riassunto: Mentre BART scorrazza sul suo skateboard viene investito dall''auto di Burns. Dopo una morte apparente riprende conoscenza in ospedale. Burns per riparare al danno offre al suo impiegato, cento miseri dollari. HOMER telefona ad una specie di azzeccagarbugli che lo aveva raccomandato di chiamarlo se avesse voluto guadagnare un po’ di soldi. Un avvocato assicura HOMER che egli può chiedere una indennità di milioni per quello che è successo. Ma BART deve mentire in tribunale sulle sue ferite. Burns capisce che perderà la causa, ed offre un risarcimento di 500.000$. MARGE vuole accettare, ma HOMER rifiuta l''accordo. Gli avvocati di Burns chiamano MARGE a testimoniare, la donna racconta tutta la verità. HOMER si domanda se riuscirà mai a perdonare quella donna, ma non appena lei entra per chiedergli scusa, lui la guarda negli occhi e capisce di amarla più che mai.' WHERE id_originale = 8945;
UPDATE archivio_items SET abstract = '(Sito) RACCONTI DI VITA. Martedì 15 giugno 2004 ore 23.40 Raitre
Nell’ultima puntata di Racconti di vita, in onda in seconda serata, si parla di violenza contro le donne dal Centro Antiviolenza della Provincia di Roma gestito dall’Associazione Differenza Donna. 
A Con una puntata speciale in onda in seconda serata Racconti di vita conclude l’edizione 2003/2004, dopo 29 puntate realizzate nei luoghi del sociale dando voce ad associazioni, gruppi, comunità e strutture pubbliche. Nel Centro Antiviolenza della Provincia di Roma gestito dall’Associazione Differenza Donna, Giovanni Anversa incontrerà le storie di donne vittime di violenza maturata dentro i nuclei familiari. Dal 1992 ad oggi sono state accolte migliaia di donne che hanno subito maltrattamenti in famiglia compiuti da mariti o conviventi, padri, fratelli, zii. Come nel caso di una ragazza macedone ridotta in schiavitù dalla famiglia del marito autore anche di una terribile violenza carnale. La trasmissione oltre a dare voce a storie di sopraffazione, seguirà in presa diretta un colloquio tra una donna fuggita di casa che ha chiesto aiuto e un operatrice volontaria. Ne emerge un insieme di testimonianze che interpellano la coscienza di tutti alla luce di un fenomeno che spesso viene minimizzato e sottovalutato anche dalle istituzioni.' WHERE id_originale = 8948;
UPDATE archivio_items SET abstract = '(centrodiascolto.it) Ordigni esplosivi. Tre ventenni sono stati arrestati a Vedelago (Treviso): per "noia" fabbricavano bombe che poi facevano esplodere in chiesa o in cabine telefoniche. Arrivavano sino a filmare con il telefonino le loro "imprese" per poi vantarsene con gli amici; intervistato, il parroco del paese, è pronto a perdonare i ragazzi..' WHERE id_originale = 8960;
UPDATE archivio_items SET abstract = '(centrodiascolto.it) Non c'' era la mafia dietro il pacco bomba che ha ucciso il figlio 18enne di un gioielliere di Sannicandro Garganico, ma una vendetta passionale, ha confessato di essere l'' autore del gesto un 25enne che ha rivelato di aver costruito i due ordigni, l'' altro non è esploso, attraverso le istruzioni trovate su internet..' WHERE id_originale = 8961;
UPDATE archivio_items SET abstract = 'Pomeriggio con i bambini in difficoltà per gli agenti della Poliziadi Stato che oggi a Torino in occasione della ricorrenza del patrono S. Michele Arcangelo, la questura del capoluogo piemontese, ha visitato i minori ospiti di una comunità cittadina che fa capo alla Caritas e all''Istituto Santa Zita che già in passato si erano trovati a lavorare insieme su casi giudiziari riguardanti i minori.' WHERE id_originale = 8978;
UPDATE archivio_items SET abstract = '7 scatenatissimi ragazzini ce la mettono tutta per boicottare la nuova governante, un padre severo e una tata, interpretata da Michelle Hunziker, che con la sua dolcezza farà innamorare tutti di sé. Poi musica, danza, canto, e tanti sorrisi. Sono gli ingredienti del musical "Tutti insieme appassionatamente", in scena in questi giorni al teatro Sistina di Roma, e poi in tournè in tutta Italia..' WHERE id_originale = 8988;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Eravamo un popolo di poeti, santi, navigatori.
Adesso che le prime due categorie sono andate un po'' in disuso, rimaniamo soprattutto un popolo di navigatori e viaggiatori. E non solo virtuali.
Prende il via l''edizione 2005 del progetto Magellano.
Un viaggio in autobus della durata di 76 giorni, 22 tappe in altrettante capitali di paesi dell''Est europeo, oltre 10.000 chilometri da macinare, tutto scrupolosamente documentato e
  trasmesso via Internet.
Sviluppato in collaborazione con l''università della Calabria e l''Aegee, l''associazione che raggruppa tutti gli studenti d''Europa, il progetto è finalizzato alla conoscenza del variegato ed entusiasmante mondo Erasmus.
Nel corso di più di due mesi 27 studenti europei, selezionati attraverso un bando di concorso internazionale, realizzeranno una serie di réportages televisivi nelle università coinvolte nell''iniziativa, aderenti al programma Socrates/Erasmus, documentando le diverse culture, le bellezze architettoniche e paesaggistiche, le testimonianze dirette dei vari protagonisti.
In continuo contatto telematico, attraverso e-mail e forum che gli permetteranno di dialogare con tutto il mondo e trasmettere le loro emozioni ad amici e colleghi, gli studenti parteciperanno a dibattiti e conferenze stampa nelle capitali visitate, e promuoveranno una serie di accordi accademico-istituzionali tesi al coinvolgimento di enti patrocinanti, università, ambasciate e istituti di cultura italiana all''estero coinvolti nel progetto stesso.' WHERE id_originale = 9027;
UPDATE archivio_items SET abstract = 'Quella bimba nata 2 anni fa, era diventata la riscossa della sua vita, la secondogenita era arrivata 16 anni dopo il primo figlio, e poteva ridare vigore al suo matrimonio, invece, è stata la causa innocente della sua fine! Gianfranco, operaio torinese di 39 anni, non sopportava l''idea di perdere quella bimba, di non poterla più vedere e abbracciare; ieri sera ha deciso di farla finita, buttandosi giù dal ponte di corso Vittorio a Torino!' WHERE id_originale = 9225;
UPDATE archivio_items SET abstract = 'Serie: FABF
Codice episodio: FABF02
Titolo episodio: TUTTI PIÙ BUONI A NATALE
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 14/12/2003
Riassunto: Siamo nel periodo natalizio e alla centrale nucleare il Sig. Burns concede gratifiche natalizie: un buono di 5 dollari per il self-service. Per ragioni ignote, il Sig. Burns dà a HOMER una figurina per BART, raffigurante un “attuale giocatore di baseball”. L’ “attuale giocatore di baseball” è Joe DiMaggio ed è la figurina del suo anno di debutto che HOMER porta alla Bottega dei Fumetti, dove il proprietario gli dà tutto quello che ha in cassa per comprarla. Con questo colpo di fortuna finanziario, la famiglia Simpsons va a fare le compere di Natale allo Springfield Heights Promenade, dove fanno shopping i ricchi. HOMER spende il rimanente della sua parte di denaro per un regalo per se stesso (un astrolabio parlante personalizzato) e non gli resta più nulla per comprare un bell’albero di Natale alla sua famiglia. MARGE e i bambini scoprono dove HOMER ha speso i soldi e sono delusi da lui. Trascorrendo la notte sul divano, HOMER guarda “Il Canto di Natale di Mr. MrGrew” e la storia infonde la sua magia in HOMER che si sveglia con l’intenzione di essere buono e altruista. HOMER inizia ad aiutare i meno fortunati e le sue buone azioni cominciano a rendere Ned Flanders geloso. Per contrastare la buona reputazione di HOMER, Ned decide di dare ad ogni persona di Springfield un regalo di Natale. HOMER vuole fare meglio di Flanders, ma su consiglio di LISA e della sua veduta buddista del mondo, HOMER decide di prendere i regali di tutti. HOMER e il Piccolo Aiutante di Babbo Natale (stile Grinch) si intrufolano in tutte le case e prendono tutti i regali. La folla inferocita trova HOMER nel centro di Springfield. Ned cerca di venire in soccorso di HOMER, ma una “stella” nel cielo li salva entrambi e restituiscono i regali. Dopo il fallito tentativo annuale di suicidio di Boe, l’intera città si unisce in un’interpretazione di "Hark the Herald Angels Sing."' WHERE id_originale = 9413;
UPDATE archivio_items SET abstract = 'Intervista a dei ragazzi su cosa ne pensano di San Valentino, se lo festeggiano, se no, se hanno un ragazzo o una ragazza, ecc..' WHERE id_originale = 9416;
UPDATE archivio_items SET abstract = 'La cooperativa: "Ladri di carrozzelle" compie 10 anni. Sono un gruppo di musicisti disabili che da tempo fanno concerti, soprattutto nelle scuole, per far conoscere l''handicap come valore, le barriere architettoniche, la tolleranza come strumento di pace e l''imprenditoria giovanile. Anna Di Stefano, voce del gruppo, parla dell''incontro con questi ragazzi eccezionali e di essersi appassionata subito a questo progetto fatto di cultura e creatività. Non solo musica quindi, ma anche laboratori musicali per disabili, attività grafiche e registrazioni di studio. Insomma si cerca di abbattere le barriere nei confronti del pregiudizio. Romano Benini parla di come Comuni, Province, Regioni e anche molti privati hanno in questi anni finanziato molti progetti verso le persone diversamente abili.' WHERE id_originale = 9417;
UPDATE archivio_items SET abstract = 'Un funerale di stato per la solennità, un funerale di popolo per la straordinaria partecipazione, mezzo milione di persone sui marciapiedi di Belfast sotto la pioggia lungo i 5 Km percorsi dal corteo con la bara di George Best, solo un grande calciatore, ma per questa gente molto di più: "Il re di cuori" dell''Irlanda del nord, il posto in cui era nato e dove è tornato per essere sepolto con una cerimonia grandiosa e commovente, è morto a soli 59 anni ucciso dall''alcool.' WHERE id_originale = 9503;
UPDATE archivio_items SET abstract = 'C''è chi ha interpretato Romeo & Giulietta facendogli usare le bombolette spray, ma anche chi ha puntato sui cartoni animati, o addirittura sui trailer, la creatività dei ragazzi di tutta Italia, ha invaso per una settimana gli schermi dei cinema di Torino: è "Sottodiciotto", il festival organizzato dalla città di Torino e dall''associazione AIACE, che mette in concorso quasi 200 film prodotti dalle scuole di tutte le regioni, oltre a organizzare proiezioni speciali e incontri sul cinema.' WHERE id_originale = 9506;
UPDATE archivio_items SET abstract = '(cinematografo.it) Rosario ha 11 anni e abita in un condominio nella periferia di Napoli insieme alla nonna Liliana, vecchia e malata. Il ragazzo passa le sue giornate trascinandosi tra sale giochi, brutte paninoteche, piccoli reati, roulette russe improvvisate sulla tangenziale. Frequenta anche un centro di accoglienza, gestito da volontari, che aiuta le famiglie in difficoltà. Le sue figure di riferimento sono così Damiano, un bullo del quartiere, e Santino, un volontario del centro, dove un giorno Rosario conosce Caterina. Si innamora di lei e la sua vita sembra cambiare in meglio, ma poi una serie di avvenimenti negativi lo getta definitivamente nelle braccia della malavita. (Film Tv) Napoli. Rosario, undici anni, abita in periferia con la nonna Liliana, una donna malata che trascorre il tempo davanti al televisore. Il bambino è il leader di un piccolo branco che passa le giornate tra sale giochi, paninoteche, piccoli reati e sfide sulla tangenziale. RECENSIONE: Andrea e Antonio Frazzi (una delle tante brave coppie di fratelli-registi in attività) alternano una ubertosa produzione televisiva al cinema. Riuscendo, almeno così mi sembra, a non confondere i due linguaggi e le due diverse scansioni del tempo narrativo. Nel 1999 hanno realizzato il loro esordio per il grande schermo, Il cielo cade, e ora propongono la loro opera seconda che si cala, di nuovo, nella testa e nei ricordi di un bambino e si appropria del suo punto di vista. Il protagonista ha undici anni, si chiama Rosario, abita nella periferia di una città del Sud (è Napoli, ma non viene mai nominata), vive una scissione priva di morale e di leggi, tra le amorevoli cure per la nonna, il volontariato in un centro di accoglienza, il primo idealizzato innamoramento per una ragazza più grande e i furti, le rapine, le scorrerie da “piccoli delinquenti crescono”, il passaggio cruciale e di fuoco alla maladolescenza camorristica. Il punto di partenza del film è l’omonimo romanzo di Diego De Silva e i Frazzi, insieme allo scrittore e agli altri sceneggiatori, hanno destrutturato il libro e ideato un doppio tragitto. Nel primo, che copre quasi tutto il racconto, Rosario è in metropolitana e va verso il suo primo omicidio e nel secondo, mentale, si illustrano i frammenti, i flash, i dettagli, gli episodi della sua sciagurata giovanissima vita. La struttura macchinosa ingabbia il film, che ha momenti visivamente ed emotivamente molto riusciti, sui binari del duplice viaggio.' WHERE id_originale = 9833;
UPDATE archivio_items SET abstract = 'Argomento della puntata l''omosessualità. Fino al 1993 l''Oraganizzazione Mondiale della Sanità includeva l''omosessualità fra le malattie mentali. Ospite in studio Daniele Scalise, giornalista e scrittore che nel 1996 ha scritto il libro "Cose dell''alrto mondo, viaggio nell''Italia gay". Spiega di come ha scoperto la sua sesualità, le attività che compie nell''ambito del suo lavoro e fa una breve storia dell''emancipazione del movimento omosessuale in Italia. Uno dei più diffusi disagi che incontra una persona che scopre la propria omosessualità è la convizione di essere unico, solo al mondo e divrso da tutti, anche per colpa del silenzio che per troppi anni ha circondato l''argomento; per fortuna oggi le cose sono cambiate radicalmente. Esiste una cultura omosesuale? E se si quali sono i segni che la contraddistinguno? Breve sequenza tratta dal film "L''apparenza inganna", film che tratta l''argomento del pregiudizio subito dai gay sul posto di lavoro. Il rischio di autoghetizzatione delle comunità omosessuali. Discussioni e sulla possibilità di adozione da parte delle coppie gay; per l''ospite l''unica cosa di cui un bambino ha bisogno è l''amore, da dove provenga questo amore è irrilevante, porta alcuni esempi di persone cresciute in situazioni familiari "particolari" e da una definizione di famiglia: "un gruppo di persone che hanno un progetto d''amore in comune". Quanto l''influeza della Chiesa Cattolica sulla politica italiana ha dirottato le scelte legislative in materia di omosessualità? Nel servizio il parere della scrittice Helena Velena. (La registrazione si interrompe)' WHERE id_originale = 9834;
UPDATE archivio_items SET abstract = 'Video intervista ad adolescenti su che musica ascoltano e che emozioni provoca in loro. "La compagna invisibile" è, appunto la musica, che accompagna le giornate dei ragazzi e gli provoca sensazioni diversissime. C''è chi ascolta punk, chi rock, chi pop, chi musica leggera o da discoteca, ma sono tutti concordi nel dire che ne sono affascinati ed emotivamente toccati. (Video molto interessante).' WHERE id_originale = 10743;
UPDATE archivio_items SET abstract = 'Dopo il salone internazionale di Milano di 2 settimane fa, il mondo della moto ha disertato il Motor Show, eppure nelle aree della fiera bolognese, s''è visto a sorpresa qualcosa di particolare, qualcosa di nuovo che potrebbe rappresentare il futuro delle 2 ruote per uso cittadino, in effetti le ruote sono 3, con le gemelle anteriori che danno un aspetto avvenieristico ad un mezzo che ha già un non so che di post-atomico: si tratta di un prototipo realizzato dalla Piaggio.' WHERE id_originale = 10788;
UPDATE archivio_items SET abstract = '(Sito Rai) I ministri Lucio Stanca, Giuliano Urbani e Maurizio Gasparri si sono impegnati per trovare soluzioni positive al fenomeno della diffusione abusiva di contenuti digitali attraverso le reti telematiche, per consentire di promuovere lo sviluppo virtuoso del mercato di tali contenuti, delle reti e delle nuove tecnologie a supporto della diffusione della creazione artistica del nostro paese.
Sulla base di un''analisi dello sviluppo del mercato dei contenuti digitali (e-content) - svolta dall''apposita commissione interministeriale presieduta da Paolo Vigevano, e sviluppatasi attraverso più di 100 ore di audizioni dei rappresentanti delle categorie interessate - si è giunti all''elaborazione delle "linee guida per l''adozione di codici di condotta ed azioni per la diffusione dei contenuti digitali nell''era di Internet", con lo scopo di creare un ambiente digitale "sicuro" che incoraggi i titolari dei contenuti a mettere a disposizione sulle reti telematiche il maggior numero possibile di opere attraenti per il consumatore, destinate alla fruizione e allo scambio da parte degli utenti. Obiettivo che può essere perseguito con una seria e determinata collaborazione tra quanti sono impegnati nella diffusione della cultura sulle reti telematiche: governo, fornitori di connettività, titolari dei diritti, case di produzione (musicale, cinematografica, televisiva, editoria, intrattenimento, ecc.) e gestori di piattaforme di distribuzione. In occasione del Festival della canzone italiana di Sanremo, al teatro Ariston, mercoledì 2 marzo, firma del "patto di Sanremo", protocollo d''intesa sulle "linee guida", da parte dei ministri Stanca, Urbani e Gasparri, e di 50 rappresentanti (presidenti e amministratori delegati) delle aziende e degli enti che vi aderiscono. Subito dopo, nella sala stampa del Festival, conferenza stampa dei tre ministri per illustrare i contenuti e gli obiettivi di questa iniziativa che, per la vastità dei settori coinvolti, non ha precedenti in Europa.' WHERE id_originale = 9029;
UPDATE archivio_items SET abstract = 'Verrà innaugurato il Museo dell''Olocausto a Gerusalemme; un nuovo modo per far conoscere ai giovani persone che un domani non ci saranno più. Presente anche Kofi Hannan a cui i Palestinesi accusano il fatto di non aver attraversato i blocchi della polizia per vedere il muro che separa israeliani e palestinesi. Ci si augura che questo evento possa contribuire a migliorare i rapporti di pace tra i due popoli.' WHERE id_originale = 9040;
UPDATE archivio_items SET abstract = 'Non incidente ma feroce, ripetuto investimento volontario quello che ha lasciato senza vita sull''asfalto una 25enne di Cossato, mentre di prima mattina andava al suo lavoro di operaia alla Tin-fin: una ditta tessile a Fila Di Trivero, alto biellese; nevicava copiosamente stamane nel biellese, e il corpo della ragazza è stato visto fra le auto del parcheggio solo dopo 2 ore, a neve sciolta: secondo i primi accertamenti effettuati dai carabinieri di Biella e dal medico legale, Debora Lizzato è stata aggredita, mentre parcheggiava la sua auto, a coltellate, poi investita e una volta a terra schiacciata da un''auto, il cui guidatore è ora ricercato in tutta la provincia.' WHERE id_originale = 9045;
UPDATE archivio_items SET abstract = 'Serie: FABF
Codice episodio: FABF08
Titolo episodio: LO ZIFF CHE VENNE A CENA
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 14/03/2004
Riassunto: HOMER tenta di portare i bambini (BART, LISA, Rod & Todd) al cinema; nel mentre Ned ha portato gli anziani a prendere un gelato per festeggiare il compleanno di Jasper. Con tutti i posti per i film per ragazzi esauriti, HOMER (su consiglio di Lenny – lui è nel film) porta i bambini a vedere “I Ri-morti” un film dell’orrore che li spaventa molto. Talmente tanto che BART e LISA iniziano a sentire rumori dalla soffitta. Cercano di investigare, ma le loro paure li tengono lontani dal salire a vedere. Danno l’incarico ad HOMER di guidare un’investigazione in soffitta e scoprono che Artie Ziff viveva lassù. Ziff spiega loro il motivo per il quale vive là: il suo lavoro su internet è fallito e ha perso tutto. Vuole restare lì fino a che non riuscirà a tornare indipendente e promette di comportarsi bene. Artie rimane, ma MARGE vede un notiziario che comunica che la SEC (Commissione per la Sicurezza e gli Scambi) lo sta cercando. Nel mentre, Artie sta giocando a poker con HOMER e i suoi amici. Artie usa il 98% delle sue rimanenti azioni per fare una puntata e HOMER vince, proprio mentre la SEC fa irruzione per arrestare Ziff. HOMER (come azionista di maggioranza) viene preso in custodia, processato e condannato a dieci anni di prigione. MARGE dice ad Artie che la sola ragione per la quale lui non piace a nessuno è perché lui pensa solo a se stesso. Ziff presto capisce che è la verità, e dopo una notte di passione con l’unica sorella Bouvier che riesce ad avere (Selma), mostra i suoi libri contabili e HOMER viene liberato.' WHERE id_originale = 9047;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Finalmente ci siamo.
Dopo mesi di estenuanti discussioni tra le parti in causa, sono state approvate dalla Camera in via definitiva le modifiche alla legge Urbani che disciplina l''uso del "file sharing".' WHERE id_originale = 9051;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) In Italia sono sicuramente i motori di ricerca i siti più visitati.
Nella classifica seguono quelli dedicati al turismo e d''informazione.
Nel costante aggiornamento delle tendenze e abitudini degli italiani, l''Istituto di studi Novatris fotografa il profilo del nostrano navigatore medio.
L''identikit tracciato dall''Osservatorio degli internauti è quello di un uomo giovane, residente al Nord, con istruzione medio-alta.
  L''indagine, effettuata con cadenza semestrale, si basa su un campione di 71.000 navigatori distribuiti su tutto il territorio italiano.
Lo studio evidenzia che ad Internet ci si connette prevalentemente da casa, utilizzando il sistema adsl o la trasmissione via cavo.
Le donne navigatrici sono il 43,5% rispetto alla più alta percentuale del 56,5% rappresentata dagli uomini.
Tra i navigatori europei, oltre agli spagnoli, agli italiani spetta il primato per la giovane età.
Mediamente i nostri internauti hanno, infatti, tra i 15 e i 24 anni.
In aumento gli acquisti on-line: passati dal 51% del 2003 al 63% del 2004.
Sulle preferenze dei siti, al primo posto - con il 56,2% - figurano i portali e i motori di ricerca.
Ma dall''indagine emerge anche che al 42% degli italiani piace consultare i siti dedicati al turismo, e nella stessa percentuale quelli dedicati ai viaggi.
Solo al terzo posto l''informazione in Rete.
E, a sorpresa, fuori dalla classifica delle preferenze degli italiani restano i siti dedicati allo sport.' WHERE id_originale = 9052;
UPDATE archivio_items SET abstract = 'La puntata di Report di questa sera prende in considerazione il nuovo progetto dell''industria di telefonia mobile "3" che da la possibiltà a chi si abbona di poter vedere la televisione sul telefonino, oltre, naturalmente al collegamento internet. La denuncia della Gabanelli riguarda soprattutto il modo in cui l''azienda ha cercato di finanziarsi, chi ci guadagna e chi ci rimette. Il no della CONSOB..' WHERE id_originale = 9078;
UPDATE archivio_items SET abstract = 'L''ha uccisa un cacciatore, colpo di scena sulla morte di Joey, 25 anni, venuta dalla Nigeria a Torino, fulminata nella sera fredda del 5 dicembre di un anno fa, ai margini di una strada al ridosso di un bosco vicino a Ciriè; il magistrato: Manuela Pedrot e i carabinieri, sono infatti convinti che a premere il grilletto del fucile calibro 21, sia stato un cacciatore.' WHERE id_originale = 9110;
UPDATE archivio_items SET abstract = 'La pratica della pena di morte è ancora in uso in molti paesi del mondo. Ieri c''è stata la giornata contro la pena di morte e in tutto il mondo si è manifestato contro questa tragica barbarie. Al telefono Sergio D''Elia dell''associazione: "Nessuno tocchi Caino" parla dell''attuale situazione della pena di morte nel mondo e soprattutto negli Stati Uniti, dato che si professano: paese democratico.' WHERE id_originale = 9118;
UPDATE archivio_items SET abstract = 'In passato aveva duettato con Tina Turner e con Cher, ora per il suo nuovo duetto Eros Ramazzotti ha scelto Anastacia, titolo: "I belong to you" (il ritmo della passione), da fine ottobre a oggi, Ramazzotti, con il suo nuovo disco: "Calma apparente" ha scalato le classifiche europee, vendendo oltre 1 milione e mezzo di copie, segno del grande successo internazionale di cui continua a godere.' WHERE id_originale = 9120;
UPDATE archivio_items SET abstract = 'Quanto è importante il sesso nel rapporto tra due teenagers? Questa è la domanda che Camila fa a Laura. La pubertà e l''adolescenza sono le fasi in cui comincia la vita sessuale, dove le maggiori energie dei ragazzi sono volte alla scoperta di questo mondo di cui tutti parlano, ma che quasi tutti gli adolescenti ancora non conoscono. La psicologa consiglia che non è necessario che la sessualità sia agita è molto importante anche solo fantasticarla o immaginarla, lasciando poi più avanti il rapporto sessuale vero e proprio. In queste prime relazioni i ragazzi cercano delle risposte alle proprie domande e paure, piaccio oppure no, quali sentimenti provo, l''intimità col partner, ecc...
Immagini di ragazzi che si baciano.' WHERE id_originale = 9126;
UPDATE archivio_items SET abstract = 'Un killer a pagamento, uno che 20 anni fa, sostiene l''accusa, accettò 1.000 Dollari dal marito di una certa Virginia Taker e la uccise, uno piuttosto odioso, si diceva innocente, accusava il figlio per quell''omicidio, lo ha ripetuto anche all''alba, poco prima che gli iniettassero il veleno a Porchmen, Mississippi; ma era un vecchietto questo John Nixon, aveva 77 anni, sarebbe comunque morto in carcere, stupida inutilità della pena capitale: che cosa ha ottenuto il Mississippi con questa esecuzione? E la California ammazzando Stanley "Tookie" Williams?' WHERE id_originale = 9139;
UPDATE archivio_items SET abstract = '(Sito Rai). L’inizio della stagione estiva di Raitre si arricchisce con un nuovo programma dedicato ai ragazzi, ancora una volta in armonia con la vocazione fondamentale della Rete: quella dell’impegno educativo e del servizio pubblico. 
L’idea di  “Un giorno per caso…” nasce proprio dal desiderio di avvicinare maggiormente i giovani ai temi dell’impegno sociale e della solidarietà.
Per i suoi contenuti, il programma è stato realizzato in modo da incentivare un’innovativa collaborazione tra rete generalista e digitale terrestre, e andrà in onda, oltre che su Raitre, anche su Rai Utile, il nuovo canale RAI realizzato per il digitale terrestre. Il programma metterà un teenager ‘viziato’ dalla società del benessere a confronto con una differente situazione di vita ‘ai margini’. Il ragazzo entrerà quindi a contatto diretto con un mondo fatto di persone che hanno percorso strade alternative, contro ogni modello prestabilito, e che con il loro operato dimostrano come sia possibile migliorare situazioni di grande sofferenza grazie a quella profonda capacità di amore e di dono che è in ognuno di noi. Da questo incontro potrà tornare illuminato o con un senso di repulsione verso il disagio altrui, ma avrà molto da scoprire…
“Un giorno per caso…”  è un vero e proprio ‘programma-realtà, ha un taglio e un linguaggio a misura di e parlato da ragazzi, che coinvolge i giovani e giovanissimi in argomenti sociali e civili, con l’obiettivo di aiutarli a confrontarsi con il mondo dei ‘grandi’ e a capire meglio che genere di persone si vuole diventare.
1° Puntata: "UNA FAMIGLIA ALLARGATA"
Celeste Breschi, incontra la famiglia Brizzolari a Cavriana (MN).
Celeste è ospite di Giampaolo e Germana Brizzolari nella loro grande casa che ospita 30 ragazzi, 30 fratelli non tutti di sangue ma di vita.
I genitori, che fanno i fornai, è composta da 3 figli naturali, 5 adottati e 22 in affido e, anche se non sono stati loro che li hanno messi al mondo li considerano tutti come propri figli proprio perche’ gli hanno insegnato una vita di dolcezza, semplicita’, rispetto, valore della famiglia e amore che ha fatto straordinaria l''esperienza di Celeste. I figli più grandi lavorano con il padre in panetteria, tutti gli altri vanno a scuola e praticano degli sport. Alcuni di questi ragazzi hanno alle spalle delle storie brutte e difficili per cui i genitori cercano di ricostruire in questi ragazzi la fiducia nei rapporti con gli altri e con la famiglia.' WHERE id_originale = 9141;
UPDATE archivio_items SET abstract = '(centrodiascolto.it) Dopo i recenti casi di cronaca che hanno visto protagonisti ragazzi violenti, il tg1 cerca di capire le motivazioni che sono alla base del fenomeno. Una ricerca Eurispes-Telefono azzurro segnala che il 20% dei ragazzi riceve minacce dai più grandi, il 18% furti, il 12% maltrattamenti. Intervistati, gli insegnanti denunciano: "La famiglia delega in maniera eccessiva il processo educativo alla scuola"..' WHERE id_originale = 9147;
UPDATE archivio_items SET abstract = 'A Torino, raduno internazionale dei tatuatori, sono arrivati in tanti da tutto il mondo e, sono tantissimi i giovani e non, che vanno a visitare questa manifestazione, se non altro si è sicuri che, in questo caso, sono assicurate le condizioni igieniche. Artistici o tradizionali, tribali o dioramici, non c''è che l''imbarazzo della scelata per chi vuol farsi tatuare.' WHERE id_originale = 9155;
UPDATE archivio_items SET abstract = 'Evo Morales, il primo Presidente Indio nella storia della Bolivia, il Paese più indio del sud America, è incoronato capo spirituale politico di tutte le comunità indigene di contadini, produttori di foglie di coca, i Cocaleros, com''è stato questo 46enne sindacalista, che non ha mai conseguito la licenza elementare, e che come first lady, ha scelto la sorella Ester, umile negoziante.' WHERE id_originale = 9163;
UPDATE archivio_items SET abstract = 'La Palma d''Oro all''ultimo Festival di Cannes per questo "(?)" una storia d''amore, ha colto di sorpresa i fratelli Darden: Luc e Gian Pierre, quanto quella per "Rosetta" ottenuta nel 1999, eppure sono in molti a paragonare il cinema austero e impegnato, dei due cineasti belgi, ex documentaristi, a quello del grande Bresson, l''emarginazione sociale e le periferie urbane tanto care ai Darden, fanno da sfondo in "(?)" a una storia di ordinaria disperazione di giovanissimi.' WHERE id_originale = 9168;
UPDATE archivio_items SET abstract = 'Da 10 giorni, da quando uno dei 5 edifici del liceo scientifico di Barcellona Pozzo di Gotto (ME) è stato chiuso per inagibilità, che i ragazzi sono scesi in piazza per protestare, è da anni che la situazione in questa scuola è precaria, e non si tiene conto di principi basilari dell''edilizia scolastica.' WHERE id_originale = 9169;
UPDATE archivio_items SET abstract = 'C''è stato un bagno di folla per Gigi D''Alessio al Mazda Palace di Torino, il cantautore impegnato nella tournè: "Quanti Amori", alla quale partecipa anche Anna Tatangelo, era atteso da una marea di fan''s, non meno di 9-10.000 ragazzi e ragazze che hanno scandito con cori e applausi la sue canzoni, prevalentemente d''amore, uno degli ultimi testi di D''Alessio è invece dedicato ai ragazzi del sabato sera, che tra alcool e discoteche rischiano di andarsi a schiantare in auto.' WHERE id_originale = 9201;
UPDATE archivio_items SET abstract = 'Ragazzi, bambini, ma anche tante donne a giocare ai videogames lo rivela una ricerca-indagine che ha anche stabilito che la fascia di età tra i 14 e i 19 anni è pari all''88% dei fruitori dei suddetti. Attualmente su 10 compratori di giochi ben 4 sono di sesso femminile, mediamente si sta alla consolle circa mezz''ora al giorno. Il 42% vivono nel Lazio, il 35% ha la licenza media e l''8% sono laureati. Il 50% delle famiglie italiane possiede una consolle che muove un giro d''affari di 600 milioni di €. Questi dati, secondo l''associazione degli psichiatri e psicologi, sono preoccupanti perché l''uso massiccio della consolle determina tra bambini e adolescenti un impoverimento delle relazioni interpersonali.                                                                                                 (sito rai) - Ragazzi e bambini ma anche tante donne a giocare ai videogames.
Un dato sorprendente quello emerso da una ricerca realizzata per conto della "Associazione editori software videoludico Italia". Su 10 degli abituali fruitori di videogiochi, ben 4 appartengono infatti al gentil sesso.' WHERE id_originale = 9203;
UPDATE archivio_items SET abstract = 'Un bel successo di spettatori per il "Festiva Cinema Gay", la 20esima edizione si è conclusa ieri, ora atteso un salto di qualità. Premiazione vivace e brillante per il "Festival di Cinema Gay", con un divertente spettacolo di cabaret, e non è mancata un''evocazione di Zapatero, che in Spagna permette il matrimonio tra omosessuali, c''è però tanta ironia e sarcasmo.' WHERE id_originale = 9205;
UPDATE archivio_items SET abstract = 'Un bambino su 4 in Italia è sovrappeso, e l''obesità è in costante aumento, lo hanno denunciato ricercatori italiani e stranieri riuniti a Verbania per discutere di come curare e prevenire l''obesità infantile, patologia che predispone a gravi rischi cardio circolatori.' WHERE id_originale = 9206;
UPDATE archivio_items SET abstract = 'Erika De Nardo, condannata a 16 anni di carcere con Omar, per il massacro di Novi Ligure, giovedì compie 21 anni, e sarà trasferita dal carcere minorile di Beccaria di Milano, ad un normale istituto di pena, forse in Piemonte.' WHERE id_originale = 9211;
UPDATE archivio_items SET abstract = 'Livorno-Lazio non è una partita come tutte le altre: è contrapposizione d''idee, scontro tra fazioni, in cui due eserciti: quello amaranto e quello biancoceleste, mettono in campo tutto il meglio e purtroppo anche tutto il peggio del loro repertorio; il Livorno ha vinto 2 a 1, e per un livornese come Lucarelli, battere la Lazio non è un semplice fatto sportivo, è un vero e proprio dovere politico, perché così era stato promesso non più tardi di giovedì scorso agli ultrà delle brigate autonome.' WHERE id_originale = 9241;
UPDATE archivio_items SET abstract = 'Il 90% dei bambini a rischio, non viene vaccinato contro l''influenza comune; mentre invece, molti a cui non servirebbe, vengono vaccinati. I bambini a rischio sono quelli che soffrono di asma, di patologie cardiache e di diabete e spesso i loro genitori sono male informati e non sanno che la vaccinazione è gratuita, per cui evitano la cura. Intervista al Prof. Pier Angelo Tovo: Osp. Infant. Regina Margherita Torino.' WHERE id_originale = 9250;
UPDATE archivio_items SET abstract = 'C''erano anche 3 sacerdoti, un vigile urbano, un sindaco, un''assistente sociale, nel giro di pedofili indagati dalla procura di Siracusa, scaricavano da internet immagini anche violente, con abusi e sevizie su bambini dai 4 agli 8 anni, , soprattutto asiatici. La procura della repubblica di Siracusa ha disposto il sequestro di oltre 400 siti internet italiani pedo-pornografici, su segnalazione dell''associazione "Telefono arcobaleno"; 11 mesi di indagine hanno permesso di identificare i 186 italiani, dopo che si erano collegati alla rete attraverso un sito super protetto aperto per soli 9 giorni.' WHERE id_originale = 9266;
UPDATE archivio_items SET abstract = 'Ancora 1° Maggio, c''è anche quello del lavoro precario, quinta edizione del: "May Day", sfilano a Milano sindacati di base, centri sociali, Disobbedienti, mondo giovanile, che si appellano appunto a San Precario. Lavoratori atipici, pensionati, immigrati, giovani e meno giovani, protagonista è il precario, in Italia ci sono 37 tipologie di lavoratori precari.' WHERE id_originale = 9269;
UPDATE archivio_items SET abstract = 'Biografia 
Le Vibrazioni sono Alessandro Deidda , Batteria (1976); Francesco Sarcina , Voce/Chitarra (1976); Marco "Garrincha" Castellani , Basso (1978); Stefano Verderi , Chitarra/Tastiere (1974). Il gruppo nasce a Milano nel ''99: le quattro Vibrazioni frequentano la stessa sala prove autogestita nell''hinterland milanese, quasi un centro sociale musicale, e sono accomunati dall''amicizia e soprattutto dallo stesso amore per la musica rock delle origini, passione che li estranea dal panorama musicale degli ultimi decenni per concentrarsi sulla musica dei loro padri, scoperta fuggendo da adolescenti dai suoni anni ''80 e mai più abbandonata. Determinante è poi l''incontro con il produttore Demetrio Sartorio, che trova la chiave di volta per far uscire Le Vibrazioni dal ghetto del ''rock da cantina'', di cui comunque mantengono orgogliosamente lo spirito ironico, scanzonato, il divertimento di stare insieme e soprattutto di suonare davvero. 
Le principali influenze del gruppo partono dalla scena britannica di fine anni ''60 e inizio anni ''70, per giungere a una sintesi fra le melodie di band come Beatles ed Animals, e il rock di Led Zeppelin, The Who e Jimi Hendrix Experience. Ma saranno la psichedelia dei Pink Floyd e il funk americano di James Brown e di Sly and the Family Stone ad avvicinare il sound de Le Vibrazioni a formazioni moderne come Jane''s Addiction, RHCP e Kula Shaker, Supergrass. 
Le Vibrazioni si propongono di proseguire un discorso iniziato, a cavallo tra fine anni ''60 e inizio anni ''70, da band italiane come New Trolls, Equipe 84 e Le Orme, e poi interrotto dal crescente successo di solisti ed interpreti. Insomma rock delle origini combinato a un raro dono melodico. 
I testi delle canzoni sono scritti da Francesco Sarcina, voce, chitarra e istrionico front man del gruppo, il quale compone pure la maggior parte delle linee melodiche; ma è nel lavoro collettivo di tutta la band che le canzoni prendono forma, nascono gli arrangiamenti, le idee di sviluppo e il ricco impasto sonoro, a tratti molto vintage, che rende il clima dell''album molto ''live rock'', anche se registrato canonicamente in studio. Studio però vissuto in modo molto tradizionale, con i ragazzi riuniti tutti insieme a registrare i pezzi. Le canzoni di Le Vibrazioni raccontano storie personali e intime che a tratti, nella riflessione, si aprono ad un''osservazione ironica, rapida ma precisa del mondo circostante. Le esperienze di vita di Francesco diventano nella scrittura storie di tutti, a volte quasi archetipi di sapore mitologico, come l''incipit di "Sani Pensieri": "Un tempo furono condannati entrambi due promessi sposi di regni diversi, che nei millenni tentarono di riunirsi ma vano fu il loro tentativo!!!" e subito si tuffano con un triplo salto logico in un quotidiano autoironico, non proprio glam rock... "Scusami tesoro, ma sono stanco di essere il tuo bersaglio mobile!" 
Altre volte fotografano momenti collettivi vissuti da tutti e quattro gli amici, come nel testo di "Non mi pare abbastanza", tentativo di raccontare e metabolizzare i sentimenti causati dalla scomparsa improvvisa e volontaria di un amico del gruppo. 
Denominatore comune di tutte le situazioni è comunque lo sguardo straniante e onirico di Francesco, capace di dipingere in pochi versi la magia e l''unicità di una comune Giulia, di una banale notte d''estate o dell''ennesimo desiderio d''amore. Capace di ribaltare, giocando con le parole, le logiche dei fusi e trasformare la banale distanza di un amore messicano in un poetico indovinello di prospettive temporali "Ma sarà perché sei così lontana... che tu già vivi sette ore nel passato di ogni mio giorno?!?" (da "Una notte d''estate"). 


TESTO DEL BRANO: "ASPETTANDO"
Aspettando 
il ciclo di stagioni 
che è sempre uguale 
Aspettando 
di rimanere 
un''altra volta da solo 
Solo 
solo come uno stupido cane 
cani che 
stanno peggio di me 
tutto il giorno aspettandomi 
non m''importa di chi soffre con me 
non m''importa di restare con te 
tu che mi usi come io uso te 
a passare il tempo senza rimpianti 
non mi dire cosa è meglio per noi 
perché il mio cuore se ne frega di te 
se ne frega di te 
se ne frega di te 
se ne frega di te 
Aspettando 
l''inevitabile bella stagione 
Aspettando 
per la macchina il giorno migliore 
ma in prigione tu 
dovresti stare tu che sei nell''errore 
di tradire così 
colui che invece 
resterebbe comunque sempre al tuo fianco 
non m''importa di chi soffre con me 
non m''importa di restare con te 
tu che mi usi come io uso te 
a passare il tempo senza rimpianti 
non mi dire cosa è meglio per noi 
perché il mio amore se ne frega di te 
Respira lentamente 
e pensa che 
c''è chi sta molto, molto peggio di te 
c''è chi viene abbandonato 
in mezzo ad una strada 
o in mezzo a un prato 
sfortunato 
se ne frega di te (x 10)' WHERE id_originale = 9274;
UPDATE archivio_items SET abstract = 'E'' ricominciato il Torino Film Festival, si svolge al cinema Lux, e in altre quattro sale: Massimo, Romano, Greenuic, Empire, le immagini scorrono già dal pomeriggio, e così via ad una delle più importanti manifestazioni di cultura, Torino e Piemonte, tra le più apprezzate in Italia; madrina d''eccezione Isabella Rossellini, con un film documento sul suo grande papà: "mio padre ha cent''anni", l''anno prossimo cade il centenario della nascita di Roberto Rossellini.' WHERE id_originale = 9288;
UPDATE archivio_items SET abstract = 'Racalmuto oltre ad essere famoso paese per aver dato i natali a Leonardo Sciascia, c''è stata per anni una sanguinosa lotta di mafia. Oggi un gruppo di ragazzi di circa 24 anni che non hanno niente a che vedere con la mafia , ma che sembrano aver imparato ad uccidere nello stesso efferato modo,  si sono macchiati dell''omicidio del giovane Simone Farrauto prima picchiandolo a sangue, poi bruciandolo con la benzina. La motivazione sembra sia il fatto che Simone fosse un ragazzo spocchioso e molto rissoso, i ragazzi si sfidano con i motorini, bevono tanto, fumano hashisc e soprattutto fanno a botte. L''atteggiamento da bulli è il motivo per cui il ragazzo è stato ucciso, almeno così sembra. Già due mesi fa Simone era finito in ospedale a causa delle botte che gli avevano dato i suoi coetanei, per cui c''erano già state le avvisaglie per una fine tragica della vicenda' WHERE id_originale = 9294;
UPDATE archivio_items SET abstract = 'Laura Pausini, una delle voci più amate dal grande pubblico, ha ottenuto un importante e anche insperato riconoscimento negli Stati Uniti. Ha vinto il premio più ambito dalle pop star latino-americane, con le note espaniche di: "Come se non fosse mai stato amore", la cantante italiana vince a sorpresa il Grammy Latin Awards per il miglior album vocale pop  femminile, un premio importante e ambitissimo che la consacra stella mondiale della musica.' WHERE id_originale = 9321;
UPDATE archivio_items SET abstract = 'La musica e la cultura zingara raccontate a Roma a Santa Maria della pietà, il vecchio manicomio diventato centro culturale, per ospitare e per far rivivere le diversità. Romina, 13 anni e frequenta la terza media, insieme ad altri amici rom è stata fotografata per un calendario. La mamma ha altri 8 figli, è per la piccola Priscilla, affetta da sindrome down che hanno lasciato il campo nomadi, troppo difficile viverci..' WHERE id_originale = 9336;
UPDATE archivio_items SET abstract = 'Il Trio Medusa, grazie alle segnalazioni di alcuni studenti dell''Università degli Studi di Chieti, ha scoperto che un professore non permette ai ragazzi di sostenere gli esami se non acquistano i suoi libri. La tattica adottata dal docente è tanto semplice quanto meschina: si fa portare il libri nuovi e li firma personalmente al momento dell''esame, così da essere sicuro che nessuno li presti ad altri. Se uno studente si presenta all''esame con un libro non nouvo viene mandato via senza nemmeno essere ascoltato.' WHERE id_originale = 9348;
UPDATE archivio_items SET abstract = 'Professore, i dati sono allarmanti…
«Le sigarette uccidono 6mila donne con il tumore al polmone. Poi ci sono i problemi di tipo arterioso o cardiaco. Tuttavia, a preoccuparci davvero, oggi, è il futuro in cui si prevede un’esplosione di tumori polmonari nel mondo femminile. Questo era tradizionalmente un problema maschile, invece da 10-15 anni c’è stata una grande diffusione del fumo fra le donne, spesso giovani. Quindi, sulla scorta dell’esperienza tragica degli uomini negli anni ’70 e ’80, quando il tumore polmonare sembrava un’epidemia, noi temiamo un disastro annunciato».
Non bisognerebbe agire, magari, già nelle  scuole elementari?
«Sì. I bambini sono ottimi interlocutori, diventano paladini convinti e i genitori ci pensano al messaggio di un bambino».
Si rivolga alle giovani donne, provi a convincerle a smettere di fumare
«Inutile dire banalmente “smettete”: non lo farebbero. Bisogna che imparino a meditare sul valore della vita. Capire quanto sia importante salvaguardarla. Smettere deve essere frutto di una convinzione che scaturisce da un pensiero profondo».
Parliamo di controlli. Cosa si deve fare?
«Sicuramente farsi vedere anche quando si ha solo un segnale debole che c''è qualcosa di sospetto nella respirazione. Tuttavia, se si è una categoria a rischio, è bene sottoporsi ogni anno a una Tac-spirale, un esame semplice che dà la certezza di individuare un eventuale tumore in una fase iniziale, quando è quasi sempre guaribile». 
 


Fascino, bellezza, sicurezza ostentata. Per anni la sigaretta fra le labbra ha rappresentato per le donne uno strumento di seduzione, quasi un segno di emancipazione. «Negli anni ’50 c’era l’idea che il fumo potesse far male», ricorda la psicologa Anna Oliverio Ferraris. «Però, proprio in quegli anni, partì una massiccia campagna pubblicitaria per cui grandi attrici fumavano liberamente e diventarono modello di riferimento. In realtà le donne dovrebbero capire che solo in apparenza fumare è segno di sicurezza: in realtà indica una difficoltà nel far fronte alle tensioni quotidiane». Il fenomeno oggi è allarmante. Le fumatrici in Italia sono quasi un milione e mezzo; quasi 6mila i casi di tumore al polmone fra le donne. E il vizio è in costante aumento, soprattutto fra le più giovani.
Il movimento “Donne contro il fumo” della fondazione Veronesi si propone di invertire questo trend, mettendo in campo autorevoli rappresentanti armate di validi argomenti contro la sigaretta. «Io sono una ex, ho fumato dai 15 ai 34 anni», ricorda la giornalista Barbara Palombelli. «So che non si può semplicemente dire che fumare è brutto, perché fumare tiene compagnia, aiuta a superare i momenti difficili. Bisogna anche dire, però, che il piacere più bello è quando si smette: si sentono i profumi, si schiarisce la pelle». 
«La nostra vita è troppo preziosa, non ci si può ridurre in cenere per il fumo», afferma l''attrice Isabella Ferrari. «È il consiglio di una donna a un''altra donna».  
 


Oggi sta bene, Agnese. A guardarla giocare con la nipotina Fabiana non si direbbe che appena cinque anni fa ha vissuto la terribile esperienza di un tumore. Che in alcuni momenti ha creduto di non farcela. «Quando l’ho scoperto è stato un dramma», racconta. «Ho fatto una toracica, su suggerimento del medico, perché avevo sempre la tosse. Quando è emerso che qualcosa non andava, mi sono sottoposta a una tac. Quando ho portato i risultati al dottore, lui l’ha guardata e mi ha detto che non ero operabile: è stata una condanna a morte».
Agnese precipita in un abisso. Ma poi, con le chemioterapie, si riaccende la speranza. «Se le reggevo, mi hanno detto, perché avrei potuto avere problemi al cuore. È stato mortificante: stavo male, avevo capogiri, non riuscivo a stare in piedi, ad arrivare da sola in bagno. A un certo punto ho detto a mia figlia “lasciami morire”».
E invece, alla fine, è andato tutto bene. L''intervento, risolutivo, Agnese lo ha fatto dopo l''ultima chemio. «Ho avuto vicino una gran donna, mia figlia, che mi ha dato tanto coraggio. E poi mi sono detta: non voglio morire, voglio fare la nonna della mia nipotina. Ho ripreso la vita normale quasi subito e puntualmente faccio controlli. Adoro camminare in montagna: se non ce la faccio mi fermo e poi riparto. Per me è come rivivere. E nel futuro, mi auguro di vedere la mia nipotina fare la comunione, la cresima e chissà, anche il matrimonio… Questo è tutto il mio mondo».  
 


Dal tumore al polmone si può guarire. L’intervento chirurgico, oggi, può essere una soluzione davvero definitiva. Ma è essenziale che il cancro venga scoperto in una fase molto iniziale. Che ci si sottoponga all’operazione quando il nodulo è talmente circoscritto da poter essere rimosso senza che abbia formato metastasi e senza comportare alcuna asportazione di parti del polmone. Insomma, una diagnosi precoce è una condizione fondamentale, per guarire e per “conservare” i propri polmoni.
«Se il tumore è preso nelle sue fasi iniziali, l’intervento diventa assai poco invasivo»,  conferma Lorenzo Spaggiari, direttore del reparto chirurgia toracica dell''Istituto Europeo di oncologia di Milano. «Questo vuol dire niente tagli dei muscoli del torace, asportazione solo di un lobo del polmone e di tutti i linfonodi». Un vantaggio che è anche estetico, visto che in questi casi l''incisione viene effettuata nel solco sottomammario e, quindi, non comporta grosse cicatrici a vista.
Diagnosi precoce, dunque. Che in alcuni casi può evitare anche la chemioterapia. Ma come accorgersi che qualcosa non va, quali sintomi devono far scattare il campanello di allarme? «L''ideale, a dire il vero, sarebbe non aspettare nemmeno il sintomo», sottolinea Spaggiari. Dunque, farsi controllare periodicamente. Specie se si è a rischio. «Uno screening che permette di identificare il tumore quando è ancora talmente piccolo che non dà sintomi ma è anche facilmente guaribile».' WHERE id_originale = 9349;
UPDATE archivio_items SET abstract = '(Sito Rai) 0.02.00  Sono trascorsi due mesi da quando Beslan ha conosciuto l''inferno... bambini e genitori riuniti in una scuola per l''avvio gioioso del nuovo ciclo e precipitati nell''abisso del terrore da un commando di uomini e donne senza pietà. Prima le minacce, poi le umiliazioni e il sangue, con le esplosioni e le sparatorie.... Il nostro inviato a Beslan Angelo Figorilli ha fatto ritorno fra le macerie di quella scuola, la scuola N°1. Il drammatico racconto di chi ha vissuto di persona quella brutta esperienza.' WHERE id_originale = 9355;
UPDATE archivio_items SET abstract = '(Sito Rai) 0.32.40 Vengono in Italia un mese l''anno, ospiti della comunità e delle famiglie più disponibii e accoglienti...Per loro non una vera vacanza, dato che frequentano comunque la scuola, ma un soggiorno terapeutico. Sono i bambini di Cernobyl, che attenuano così, almeno in parte, i danni da cesio radiottivo....' WHERE id_originale = 9357;
UPDATE archivio_items SET abstract = '(Sito Rai) La reginetta del 2004, la cilena Katty Ko, è stata appena archiviata come prima "miss digitale del web".
Ma le fascinose dive virtuali già si preparano alla competizione del prossimo anno, dove stavolta i professionisti del design verranno sfidati anche da semplici creatori dilettanti.
Grazie al kit "topgirl fai da te".' WHERE id_originale = 9367;
UPDATE archivio_items SET abstract = 'La parola psichedelia significa: rendere visibile l''anima. Questo servizio è un percorso, appunto, che ripercorre le origini e l''utilizzo della psichedelia
come movimento artistico e culturale. L''assunzione dell''LSD, della mescalina, la rivoluzione sessuale e studentesca, la beat genation, gli artisti che fanno contro cultura, la musica, sono tutti aspetti del movimento psichedelico che prende piede negli Stati Uniti all''inizio degli anni 60.
Visita alla mostra di Carpi intitolata: "Kaleidoscope" sulla psichedelia dal 1964 al 1974. Si parla di musica con i Beatles, Frank Zappa, Bob Dylan, Doors, Jimi Hendrix, Jefferson Airplane, Pink Floyd. Raffronti con gli stessi anni di quello che avveniva in Italia. Il Vietnam, l''Oriente non più misterioso. Importanti sono le applicazioni soprattutto per quanto riguarda l''arte, le copertine dei dischi, i fumetti, la moda giovanile e, grazie ad alcuni personaggi come Ettore Sottsass, Fernanda Pivano, i gruppi beat anche l''Italia viene in contatto con questo movimento. Intervista a Claudio Rocchi: esempio di musica italiana psichedelica. Occorre ricordare che fino al 1966 Lsd era legale, poi viene bloccato e criminalizzato.' WHERE id_originale = 9369;
UPDATE archivio_items SET abstract = 'Billi è una bambina inglese di 11anni che con i suoi genitori si era recata in vacanza alle Maldive. A scuola aveva studiato il formarsi degli Utzunami, così quando ha visto ritirarsi il mare ha dato l''allarme salvando  un centinaio di persone. Sophia è una bambina Malese di appena 20 giorni. I genitori l''avevano messa a riposare su un materassino gonfiabile all''interno del loro ristorante, così quando il mare lo ha travolto, lei è rimasta a galla, i genitori emersi dopo l''onda hanno sentito la piccola piangere e sono riusciti a trovarla sana e salva. Un altro bimbo di appena 18 mesi siè salvato grazie al suo materassino, portato al largo di Caolak (in Tailandia), dall''onda, è stato trovato da un signore Indiano, quest''uomo che si trovava su di una imbarcazione, lo ha tratto in salvo e in seguito portato in ospedale dove si è riunito con i suoi genitori. Nimami è una bambina dello Sri Lanca di 4 anni viaggiava in treno con sua sorella e i suoi genitori, l''onda ha travolto il treno lanciandolo in mare, lei è l''unica sopravvissuta della sua famiglia, inseguito portata all''ospedale è stata trovata e raggiunta dal nonno. An che gli Italiani sopravvissuti stanno tornando a casa e il numero dei superstiti continua ad aumentare.-' WHERE id_originale = 9371;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Formare, aggiornare o riqualificare i milioni di dipendenti della pubblica amministrazione per metterli periodicamente al passo con i tempi che cambiano è sempre stato un problema, per altro decisamente dispendioso.
Oggi con "Rai utile" - la tv interattiva della Rai che sta facendo da pioniere nel
  mondo che verrà del digitale terrestre - studiare e formarsi non è mai stato così semplice.
La formazione è dunque basata su una piattaforma che consente una forte interattività.
Un tutor in studio guida il pubblico facendolo interagire con la lezione dell''esperto, e ognuno, dopo essersi registrato, semplicemente utilizzando il tanto caro telecomando, potrà consultare altre risorse disponibili sul tema, ricevere il suo test e rispondere alle domande grazie ad un centro servizi che smista il flusso delle informazioni.
Alla fine riceverà anche un attestato di partecipazione e relativo punteggio acquisito.
Comodità, risparmio, semplicità d''uso sono le grandi qualità della formazione a distanza che passa dalla tv.
Insomma, ora enti e dipendenti non hanno più scuse.
Aggiornare e migliorare la qualità del proprio lavoro, oltre ad essere utile, oggi è anche facile, come guardare la tv.' WHERE id_originale = 9383;
UPDATE archivio_items SET abstract = '(PRESO DA SITO RAI) Grazie alle tecnologie cresce il volume d''affari anche della pornografia.
Il consumatore abituale è ormai raggiungibile 24 ore su 24 attraverso il computer e il telefonino.
Dal rapporto presentato a Roma dall''istituto Eurispes, con il patrocinio del Pontificio Consiglio per le comunicazioni sociali, l''evoluzione tecnologica ha determinato la crescita del fatturato globale del mercato della pornografia.
Circa 1.000 milioni di euro il valore medio annuo.
Le strategie di mercato non puntano più ad allargare la cerchia dei consumatori, ma bensì a fornire una sorta di accudimento ovunque si trovino e attraverso tutti i mezzi di
  comunicazione, quelli tradizionali e quelli tecnologicamente più avanzati.
Ne sono un esempio i videotelefonini satellitari sempre più utilizzati come supporti di prodotti di porno virtuale.
Secondo le stime dell''istituto di ricerca, ogni giorno 20.000 nuovi siti porno compaiono sul web in tutto il pianeta.
Ma il loro fatturato, almeno in Italia, è sceso già dal 2003, dopo la notizia scandalo delle "bollette anomale".
Tutta la pornorete in lingua italiana ha perso utenti-clienti, diventati sospettosi e restii.
Ma il 2004 è stato anche l''anno in cui decolla il volume d''affari del porno fruibile dalle pay tv, con un''impennata degli abbonamenti alle televisioni che trasmettono film e altri programmi hard.
Nelle classifiche mondiali sullo spamming, poi, la pubblicità pornografica è seconda solo a quella economico-finanziaria.
L''ultimo triste capitolo del rapporto riguarda la pornografia minorile.
I paesi nei quali si collocano la maggior parte dei server dei siti di pornografia minorile sono gli Usa, seguiti a grande distanza dal Canada e dall''Olanda.' WHERE id_originale = 9385;
UPDATE archivio_items SET abstract = 'Serie: FABF
Codice episodio: FABF15
Titolo episodio: CHI DI SPADA FERISCE, DI TORTA PERISCE
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 02/05/2004
Riassunto: HOMER è intrigato da uno spot che parla di una competizione che permetterà al vincitore, chi troverà un biglietto d’oro, di andare a visitare la “Fabbrica di Pancetta Affumicata del Contadino Billy”. HOMER compra molti prodotti di maiale, ma riesce a trovare solo un biglietto d’argento, che gli permette di fare da giudice alla gara dei maiali alla fiera della contea. Quando HOMER vede che, all’entrata di LISA alla gara per i coperti, viene compiuta un’ingiustizia , decide di entrare in azione. Ricordando l’avvertimento del commissario Winchester riguardo ad un attacco criminale, HOMER si traveste da “Uomo Torta” e lancia una torta in faccia come vendetta. Poi scompare il più velocemente possibile, lasciando Springfield a domandarsi se lo rivedrà di nuovo. Quando BART viene truffato dall’uomo dei fumetti, l’ “Uomo Torta” lancia alcuni “cedri della giustizia”. La polizia decide che l’ “Uomo Torta” deve essere fermato e gli sparano alla sua successiva apparizione. Lui trova del tempo per i suoi sentimenti, salva MARGE e la bacia, anche se lei gli dice che è una donna sposata. Più tardi a casa, un ferito HOMER promette a LISA (che ha scoperto il suo travestimento) che la smetterà con la sua vendetta a suon di torte. Però quando il Sig. Burns va troppo oltre, l’ “Uomo Torta” fa un’altra apparizione, ma la sua fuga dalla centrale viene impedita dal suo stesso lazzaronismo. Il Sig. Burns lo trasforma nel suo sicario personale. HOMER si trova in un dilemma, quando il Sig. Burns vuole che lanci una torta in faccia all’eroe buddista di LISA: il Dalai Lama. Quando si smaschera di fronte alla folla, nessuno crede che lui avrebbe potuto essere l’ “Uomo Torta”, solo la sua famiglia gli crede.' WHERE id_originale = 9386;
UPDATE archivio_items SET abstract = 'Serie: FABF
Codice episodio: FABF17
Titolo episodio: ALLA FACCIA DELLA BANDIERA
Stagione numero: 15
Anno di produzione: 2003/2004
Prima messa onda in Tv (USA): 16/05/2004
Riassunto: E’ il giorno dell’iniezione e BART tenta di evitare l’ago. Il Dr Hibbert riesce a terminare il lavoro, ma BART come effetto collaterale si ritrova temporaneamente sordo e cerca di trarne più vantaggi che può. Alla scuola elementare di Springfield si sta svolgendo l’annuale torneo di basket degli asini. Durante l’inno nazionale un asino mangia i calzoncini di BART, lasciandolo con il suo sedere nudo esposto verso la bandiera. Martin scatta una fotografia e tutti i presenti sono oltraggiati dal suo comportamento. Il risultato è che la famiglia Simpson diventa molto impopolare. Per rimediare vanno su un canale di notizie via cavo ma riescono solo a finire in un buco ancora più profondo quando il conduttore riesce a rigirare le parole di MARGE, dicendo che Springfield odia l’America. La pubblicità negativa obbliga il sindaco Quimby a cambiare il nome della città in Liberty-Ville e a rendere ogni cosa patriottica. La famiglia è arrestata per aver violato l''emendamento “Il governo conosce ciò che è meglio” ed è portata in un centro di rieducazione, ma l’ultimo Democratico iscritto dice loro come fuggire. Durante il loro numero musicale scappano attraverso un tunnel, ma si rendono conto di essere finiti ad Alcatraz. Vengono salvati da un cargo francese di passaggio e portati in Francia. Dopo essere stati là un po’ capiscono che gli manca l’America e tornano indietro come immigrati clandestini. 
Regista: STEVEN DEAN MOORE
Sceneggiatori: JOHN FRINK' WHERE id_originale = 9389;